name = "FTAPTheorem42"
version = "0.1.1"
keywords = ["math"]
defaultTargets = ["FTAPTheorem42"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[lean_lib]]
name = "FTAPTheorem42"
