/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/
import FTAPTheorem42.Stochastic.Martingale.Basic.CompatibleLocalMartingaleGluing
import FTAPTheorem42.Stochastic.Martingale.Regularization.ConditionalExpectationFactorialCompatibility
import FTAPTheorem42.Stochastic.Martingale.Basic.FiniteGridMartingaleProcess
import FTAPTheorem42.Stochastic.Decomposition.Source.StoppedSkeletonLimit

/-!
# A global càdlàg conditional-expectation martingale

The stopped factorial-grid versions at horizons `n + 2`, localized at
`n + 1`, are everywhere càdlàg true martingales. Their overlap law lets the
compatible-local-martingale construction glue them into one global process.
The glued process is a fixed-time modification of the original conditional
expectation and hence is itself a true martingale.
-/

open Filter MeasureTheory Set Topology
open scoped ENNReal NNReal ProbabilityTheory

namespace FTAPTheorem42

variable {Omega : Type*} [MeasurableSpace Omega]

namespace HorizonFactorialGrid

private def cadlagCoordinateStop (n : Nat) : NNReal :=
  (n + 1 : Nat)

private def cadlagCoordinateTerminal (n : Nat) : NNReal :=
  (n + 2 : Nat)

private theorem cadlagCoordinateStop_lt_terminal (n : Nat) :
    cadlagCoordinateStop n < cadlagCoordinateTerminal n := by
  unfold cadlagCoordinateStop cadlagCoordinateTerminal
  exact_mod_cast Nat.lt_succ_self (n + 1)

private def cadlagCoordinateLocalizer
    (_F : Filtration NNReal (inferInstance : MeasurableSpace Omega)) :
    Nat -> Omega -> WithTop NNReal :=
  fun n _ => cadlagCoordinateStop n

private theorem cadlagCoordinateLocalizer_isLocalizingSequence
    {mu : Measure Omega}
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega)) :
    ProbabilityTheory.IsLocalizingSequence F
      (cadlagCoordinateLocalizer F) mu where
  isStoppingTime n := isStoppingTime_const F (cadlagCoordinateStop n)
  mono := Filter.Eventually.of_forall fun _ n m hnm => by
    change ((n + 1 : Nat) : WithTop NNReal) ≤ (m + 1 : Nat)
    exact_mod_cast Nat.add_le_add_right hnm 1
  tendsto_top := Filter.Eventually.of_forall fun _ =>
    WithTop.tendsto_coe_atTop.comp
      (tendsto_natCast_atTop_atTop.comp (tendsto_add_atTop_nat 1))

/-- The conditional-expectation martingale generated by an `L²` terminal
variable has an everywhere càdlàg martingale modification. -/
theorem exists_cadlagMartingaleVersion_condExpMartingaleProcess
    {mu : Measure Omega} [IsProbabilityMeasure mu]
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (f : Lp Real 2 mu) :
    ∃ Y : Process Omega,
      Martingale Y F mu ∧
      (∀ omega t, ContinuousWithinAt (Y · omega) (Ici t) t) ∧
      ProcessHasLeftLimits Y ∧
      (∀ t, Y t =ᵐ[mu] condExpMartingaleProcess mu F f t) := by
  have hCoordinateExists (n : Nat) :=
    exists_stoppedFactorialGridRightLimit_condExp_cadlagMartingale
      F hUsual f (cadlagCoordinateStop_lt_terminal n)
  choose X hXMartingale hXRight hXLeft hXRaw using hCoordinateExists
  let tau := cadlagCoordinateLocalizer (Omega := Omega) F
  have hTau : ProbabilityTheory.IsLocalizingSequence F tau mu :=
    cadlagCoordinateLocalizer_isLocalizingSequence F
  have hCompat (n m : Nat) : ProcessIndistinguishable mu
      (MeasureTheory.stoppedProcess (X n) (min (tau n) (tau m)))
      (MeasureTheory.stoppedProcess (X m) (min (tau n) (tau m))) := by
    let Rn := cadlagCoordinateStop n
    let Rm := cadlagCoordinateStop m
    let V := min Rn Rm
    let Tn := cadlagCoordinateTerminal n
    let Tm := cadlagCoordinateTerminal m
    have hVTn : V < Tn := (min_le_left Rn Rm).trans_lt
      (cadlagCoordinateStop_lt_terminal n)
    have hVTm : V < Tm := (min_le_right Rn Rm).trans_lt
      (cadlagCoordinateStop_lt_terminal m)
    have hBase := stoppedFactorialGridRightLimit_condExp_indistinguishable
      F hUsual f hVTn hVTm
    have hRawN : ProcessIndistinguishable mu
        (MeasureTheory.stoppedProcess
          (stoppedFactorialGridRightLimit
            (condExpMartingaleProcess mu F f) Tn Rn)
          (min (tau n) (tau m)))
      (stoppedFactorialGridRightLimit
          (condExpMartingaleProcess mu F f) Tn V) := by
      exact Filter.Eventually.of_forall fun omega t => by
        change MeasureTheory.stoppedProcess
            (stoppedFactorialGridRightLimit
              (condExpMartingaleProcess mu F f) Tn Rn)
            (fun _ : Omega => (V : WithTop NNReal)) t omega = _
        rw [stoppedProcess_const_apply]
        unfold stoppedFactorialGridRightLimit
        rw [min_eq_left ((min_le_right t V).trans
          (min_le_left Rn Rm))]
    have hRawM : ProcessIndistinguishable mu
        (MeasureTheory.stoppedProcess
          (stoppedFactorialGridRightLimit
            (condExpMartingaleProcess mu F f) Tm Rm)
          (min (tau n) (tau m)))
        (stoppedFactorialGridRightLimit
          (condExpMartingaleProcess mu F f) Tm V) := by
      exact Filter.Eventually.of_forall fun omega t => by
        change MeasureTheory.stoppedProcess
            (stoppedFactorialGridRightLimit
              (condExpMartingaleProcess mu F f) Tm Rm)
            (fun _ : Omega => (V : WithTop NNReal)) t omega = _
        rw [stoppedProcess_const_apply]
        unfold stoppedFactorialGridRightLimit
        rw [min_eq_left ((min_le_right t V).trans
          (min_le_right Rn Rm))]
    exact (hXRaw n).stoppedProcess (min (tau n) (tau m)) |>.trans <|
      hRawN.trans <| hBase.trans <|
        hRawM.symm.trans ((hXRaw m).stoppedProcess
          (min (tau n) (tau m))).symm
  obtain ⟨Y, hYAdapted, _, hYRight, hYLeft, hYStopped⟩ :=
    CompatibleLocalMartingaleGluing.exists_cadlag_localMartingale
      hUsual hTau hXMartingale hXRight hXLeft hCompat
  have hYEq (t : NNReal) :
      Y t =ᵐ[mu] condExpMartingaleProcess mu F f t := by
    let n := Nat.ceil t
    have htR : t ≤ cadlagCoordinateStop n := by
      calc
        t ≤ (Nat.ceil t : NNReal) := Nat.le_ceil t
        _ ≤ cadlagCoordinateStop n := by
          simp only [n, cadlagCoordinateStop]
          exact_mod_cast Nat.le_add_right (Nat.ceil t) 1
    have htT : t < cadlagCoordinateTerminal n :=
      htR.trans_lt (cadlagCoordinateStop_lt_terminal n)
    have hStopped := (hYStopped n).eventuallyEq_at t
    have hCoordinate := (hXRaw n).eventuallyEq_at t
    have hSelected := factorialGridRightLimit_condExpMartingaleProcess_ae_eq
      F hUsual f (cadlagCoordinateTerminal n) t htT
    filter_upwards [hStopped, hCoordinate, hSelected]
      with omega hStoppedOmega hCoordinateOmega hSelectedOmega
    change Y (min t (cadlagCoordinateStop n)) omega =
      X n (min t (cadlagCoordinateStop n)) omega at hStoppedOmega
    rw [min_eq_left htR] at hStoppedOmega
    simp only [stoppedFactorialGridRightLimit, min_eq_left htR]
      at hCoordinateOmega
    exact hStoppedOmega.trans (hCoordinateOmega.trans hSelectedOmega)
  have hYMartingale : Martingale Y F mu :=
    (martingale_condExpMartingaleProcess mu F f).congr hYAdapted
      fun t => (hYEq t).symm
  exact ⟨Y, hYMartingale, hYRight, hYLeft, hYEq⟩

/-- The common stopped Doob convexification can be chosen with an everywhere
càdlàg martingale process realizing all martingale coordinates on the
canonical skeleton. -/
theorem exists_common_stoppedComponentConvexification_cadlagMartingaleProcess
    {S : Process Omega}
    {F : Filtration NNReal (inferInstance : MeasurableSpace Omega)}
    {mu : Measure Omega} [IsProbabilityMeasure mu]
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (source : BoundedSemimartingaleSource S F mu)
    {a : Real} (ha : 0 ≤ a) (T : NNReal) :
    ∃ (w : ∀ n, TailConvexWeights n)
      (predictableLimit martingaleLimit : Nat → Lp Real 2 mu)
      (M : Process Omega),
      (∀ j, Tendsto
        (fun n => (w n).applyVector (fun r =>
          stoppedPredictableApproximationToLp source ha T
            (stoppedLimitSkeleton T j).1 (stoppedLimitSkeleton T j).2 r))
        atTop (𝓝 (predictableLimit j))) ∧
      (∀ j, Tendsto
        (fun n => (w n).applyVector (fun r =>
          stoppedMartingaleApproximationToLp source ha T
            (stoppedLimitSkeleton T j).1 (stoppedLimitSkeleton T j).2 r))
        atTop (𝓝 (martingaleLimit j))) ∧
      Martingale M F mu ∧
      (∀ omega t, ContinuousWithinAt (M · omega) (Ici t) t) ∧
      ProcessHasLeftLimits M ∧
      ∀ i, M (stoppedLimitSkeleton T i).1 =ᵐ[mu]
        (martingaleLimit i : Omega → Real) := by
  obtain ⟨w, predictableLimit, martingaleLimit,
      hPredictable, hMartingale, hSkeletonMartingale⟩ :=
    exists_common_stoppedComponentConvexification_skeleton_martingale
      source ha T
  let terminal := stoppedLimitTerminalIndex T
  obtain ⟨M, hMMartingale, hMRight, hMLeft, hMVersion⟩ :=
    exists_cadlagMartingaleVersion_condExpMartingaleProcess F hUsual
      (martingaleLimit terminal)
  refine ⟨w, predictableLimit, martingaleLimit, M,
    hPredictable, hMartingale, hMMartingale, hMRight, hMLeft, ?_⟩
  intro i
  have hiT : (stoppedLimitSkeleton T i).1 ≤
      (stoppedLimitSkeleton T terminal).1 := by
    rw [show (stoppedLimitSkeleton T terminal).1 = T by
      simp only [terminal, stoppedLimitSkeleton_terminalIndex]]
    exact (stoppedLimitSkeleton T i).2
  have hLaw := hSkeletonMartingale i terminal hiT
  have hTerminalMem : MemLp
      (martingaleLimit terminal : Omega → Real) 2 mu :=
    Lp.memLp (martingaleLimit terminal)
  have hBridge := hTerminalMem.condExpL2_ae_eq_condExp (𝕜 := Real)
    (F.le (stoppedLimitSkeleton T i).1)
  rw [Lp.toLp_coeFn (martingaleLimit terminal) hTerminalMem] at hBridge
  have hLawFun := congrArg
    (fun z : Lp Real 2 mu => (z : Omega → Real)) hLaw
  filter_upwards [hMVersion (stoppedLimitSkeleton T i).1, hBridge] with
      omega hVersionOmega hBridgeOmega
  rw [hVersionOmega]
  change mu[(martingaleLimit terminal : Omega → Real) |
      F (stoppedLimitSkeleton T i).1] omega = _
  rw [← hBridgeOmega]
  exact congrFun hLawFun omega

end HorizonFactorialGrid

end FTAPTheorem42
