/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/
import FTAPTheorem42.Stochastic.Martingale.Regularization.MartingaleFactorialGridRightContinuity
import FTAPTheorem42.Stochastic.Process.NullSetProcessRegularization

/-!
# Identifying the factorial-grid right limit of a conditional expectation

Under the usual conditions, the selected pathwise right limit of the
conditional-expectation martingale agrees almost everywhere at every fixed
preterminal time with the original conditional expectation.
-/

namespace FTAPTheorem42

open Filter MeasureTheory Topology
open scoped ENNReal NNReal ProbabilityTheory

variable {Omega : Type*} [MeasurableSpace Omega]

/-- The raw conditional-expectation martingale generated by an `L²` terminal
random variable. -/
noncomputable def condExpMartingaleProcess
    (mu : Measure Omega)
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (f : Lp Real 2 mu) : Process Omega :=
  fun t => mu[(f : Omega -> Real) | F t]

theorem martingale_condExpMartingaleProcess
    (mu : Measure Omega)
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (f : Lp Real 2 mu) [SigmaFiniteFiltration mu F] :
    Martingale (condExpMartingaleProcess mu F f) F mu :=
  martingale_condExp (f : Omega -> Real) F mu

theorem condExpL2Value_ae_eq_condExpMartingaleProcess
    {mu : Measure Omega}
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (f : Lp Real 2 mu) (t : NNReal) [IsFiniteMeasure mu] :
    (condExpL2Value mu (F t) (F.le t) f : Omega -> Real) =ᵐ[mu]
      condExpMartingaleProcess mu F f t := by
  have hBridge := (Lp.memLp f).condExpL2_ae_eq_condExp
    (E := Real) (𝕜 := Real) (F.le t)
  rw [Lp.toLp_coeFn f (Lp.memLp f)] at hBridge
  exact hBridge

/-- At every fixed preterminal time, the factorial-grid right-limit version
of a conditional-expectation martingale equals the original process almost
everywhere. -/
theorem factorialGridRightLimit_condExpMartingaleProcess_ae_eq
    {mu : Measure Omega} [IsFiniteMeasure mu]
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (f : Lp Real 2 mu) (T t : NNReal) (ht : t < T) :
    HorizonFactorialGrid.factorialGridRightLimit
        (condExpMartingaleProcess mu F f) T t =ᵐ[mu]
      condExpMartingaleProcess mu F f t := by
  let M := condExpMartingaleProcess mu F f
  let s := HorizonFactorialGrid.factorialGridRightApproxTime T t
  have hM : Martingale M F mu :=
    martingale_condExpMartingaleProcess mu F f
  have hTerminal : MemLp (M T) (2 : ENNReal) mu := by
    exact (Lp.memLp f).condExp (by norm_num)
  have hLp : Tendsto (fun n =>
      condExpL2Value mu (F (s n)) (F.le (s n)) f) atTop
      (nhds (condExpL2Value mu (F t) (F.le t) f)) := by
    apply tendsto_condExpL2Value_of_tendsto_nhdsGT F hUsual f t s
    · intro n
      exact (HorizonFactorialGrid.lt_factorialGridRightApproxTime ht n).le
    · exact HorizonFactorialGrid.tendsto_factorialGridRightApproxTime
        T t ht.le
  have hInMeasure : TendstoInMeasure mu (fun n omega => M (s n) omega)
      atTop (M t) := by
    apply TendstoInMeasure.congr
      (fun n => condExpL2Value_ae_eq_condExpMartingaleProcess F f (s n))
      (condExpL2Value_ae_eq_condExpMartingaleProcess F f t)
    exact tendstoInMeasure_of_tendsto_Lp hLp
  exact HorizonFactorialGrid.Martingale.factorialGridRightLimit_ae_eq_of_sequence
    hM T t ht hTerminal s
    (HorizonFactorialGrid.factorialGridRightApproxTime_mem T t)
    (HorizonFactorialGrid.lt_factorialGridRightApproxTime ht)
    (HorizonFactorialGrid.tendsto_factorialGridRightApproxTime T t ht.le)
    hInMeasure

end FTAPTheorem42

namespace FTAPTheorem42

/-!
## Compatibility of finite-horizon conditional-expectation regularizations

Two factorial-grid right-limit versions constructed with different terminal
horizons agree indistinguishably after stopping strictly inside both
horizons.  Fixed-time agreement with the raw conditional expectation is
simultaneous on the countable right-dense skeleton, and right continuity then
propagates it to every time.
-/

open Filter MeasureTheory Set Topology
open scoped ENNReal NNReal ProbabilityTheory

variable {Omega : Type*} [MeasurableSpace Omega]

namespace HorizonFactorialGrid

open FTAPTheorem42.ProcessNullSetRegularization

/-- Stopping a martingale at a deterministic `NNReal` time preserves the
martingale property. This elementary fact does not require path regularity. -/
theorem Martingale.deterministicallyStopped_nnreal
    {mu : Measure Omega}
    {F : Filtration NNReal (inferInstance : MeasurableSpace Omega)}
    [SigmaFiniteFiltration mu F]
    {M : Process Omega} (hM : Martingale M F mu) (R : NNReal) :
    Martingale (fun t omega => M (min t R) omega) F mu := by
  constructor
  · intro t
    exact (hM.stronglyMeasurable (min t R)).mono
      (F.mono (min_le_left t R))
  · intro i j hij
    change mu[M (min j R) | F i] =ᵐ[mu] M (min i R)
    by_cases hjR : j ≤ R
    · rw [min_eq_left hjR, min_eq_left (hij.trans hjR)]
      exact hM.condExp_ae_eq hij
    have hRj : R ≤ j := le_of_not_ge hjR
    by_cases hRi : R ≤ i
    · rw [min_eq_right hRi, min_eq_right hRj]
      have hCond := condExp_of_stronglyMeasurable (F.le i)
        ((hM.stronglyMeasurable R).mono (F.mono hRi))
        (hM.integrable R)
      exact Filter.Eventually.of_forall fun omega => congrFun hCond omega
    · have hiR : i ≤ R := le_of_not_ge hRi
      rw [min_eq_left hiR, min_eq_right hRj]
      exact hM.condExp_ae_eq hiR

/-- The factorial-grid right-limit version, stopped at a deterministic time. -/
noncomputable def stoppedFactorialGridRightLimit
    (M : Process Omega) (T R : NNReal) : Process Omega :=
  fun t omega => factorialGridRightLimit M T (min t R) omega

/-- Under the usual conditions, the stopped factorial-grid version of a
conditional-expectation martingale is strongly adapted. -/
theorem stoppedFactorialGridRightLimit_condExp_stronglyAdapted
    {mu : Measure Omega} [IsFiniteMeasure mu]
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (f : Lp Real 2 mu) {T R : NNReal} (hRT : R < T) :
    StronglyAdapted F
      (stoppedFactorialGridRightLimit
        (condExpMartingaleProcess mu F f) T R) := by
  intro t
  let s := min t R
  have hsT : s < T := (min_le_right t R).trans_lt hRT
  have hEq := factorialGridRightLimit_condExpMartingaleProcess_ae_eq
    F hUsual f T s hsT
  have hRaw : StronglyMeasurable[F t]
      (condExpMartingaleProcess mu F f s) :=
    (martingale_condExpMartingaleProcess mu F f).stronglyMeasurable s |>.mono
      (F.mono (min_le_left t R))
  have hAE : AEStronglyMeasurable[F t]
      (stoppedFactorialGridRightLimit
        (condExpMartingaleProcess mu F f) T R t) mu :=
    hRaw.aestronglyMeasurable.congr hEq.symm
  exact (measurable_of_aestronglyMeasurable_of_nullSets
    (fun A hA => hUsual.measurableSet_of_null zero_le hA) hAE).stronglyMeasurable

/-- The stopped factorial-grid version is itself a true martingale. -/
theorem stoppedFactorialGridRightLimit_condExp_martingale
    {mu : Measure Omega} [IsFiniteMeasure mu]
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (f : Lp Real 2 mu) {T R : NNReal} (hRT : R < T) :
    Martingale
      (stoppedFactorialGridRightLimit
        (condExpMartingaleProcess mu F f) T R) F mu := by
  let M := condExpMartingaleProcess mu F f
  have hM : Martingale M F mu := martingale_condExpMartingaleProcess mu F f
  apply (HorizonFactorialGrid.Martingale.deterministicallyStopped_nnreal
    hM R).congr
    (stoppedFactorialGridRightLimit_condExp_stronglyAdapted
      F hUsual f hRT)
  intro t
  have hsT : min t R < T := (min_le_right t R).trans_lt hRT
  exact (factorialGridRightLimit_condExpMartingaleProcess_ae_eq
    F hUsual f T (min t R) hsT).symm

/-- The stopped factorial-grid version is almost surely right-continuous and
has left limits on the whole time axis. -/
theorem stoppedFactorialGridRightLimit_condExp_isCadlag_ae
    {mu : Measure Omega} [IsFiniteMeasure mu]
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    [SigmaFiniteFiltration mu F]
    (f : Lp Real 2 mu) {T R : NNReal} (hRT : R < T) :
    ∀ᵐ omega ∂mu,
      (∀ t, ContinuousWithinAt
        (stoppedFactorialGridRightLimit
          (condExpMartingaleProcess mu F f) T R · omega) (Ici t) t) ∧
      (∀ t, Tendsto (fun s => stoppedFactorialGridRightLimit
          (condExpMartingaleProcess mu F f) T R s omega)
        (nhdsWithin t (Iio t))
        (nhds (Function.leftLim (fun s => stoppedFactorialGridRightLimit
          (condExpMartingaleProcess mu F f) T R s omega) t))) := by
  let M := condExpMartingaleProcess mu F f
  have hM : Martingale M F mu := martingale_condExpMartingaleProcess mu F f
  have hTerminal : MemLp (M T) (2 : ENNReal) mu :=
    (Lp.memLp f).condExp (by norm_num)
  filter_upwards
    [Martingale.factorialGridRightLimit_isCadlagOn_ae hM T hTerminal]
      with omega hRegular
  constructor
  · exact continuousWithinAt_deterministicallyStopped_of_before hRT
      hRegular.1
  · exact deterministicallyStopped_hasLeftLimits_of_before
      (fun s hs hsR => hRegular.2 s hs (hsR.trans hRT.le))

/-- The stopped selected process has an everywhere càdlàg martingale
version. It remains indistinguishable from the pathwise right-limit
construction. -/
theorem exists_stoppedFactorialGridRightLimit_condExp_cadlagMartingale
    {mu : Measure Omega} [IsFiniteMeasure mu]
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (f : Lp Real 2 mu) {T R : NNReal} (hRT : R < T) :
    ∃ Y : Process Omega,
      Martingale Y F mu ∧
      (∀ omega t, ContinuousWithinAt (Y · omega) (Ici t) t) ∧
      ProcessHasLeftLimits Y ∧
      ProcessIndistinguishable mu Y
        (stoppedFactorialGridRightLimit
          (condExpMartingaleProcess mu F f) T R) := by
  let X := stoppedFactorialGridRightLimit
    (condExpMartingaleProcess mu F f) T R
  have hXAdapted : StronglyAdapted F X :=
    stoppedFactorialGridRightLimit_condExp_stronglyAdapted
      F hUsual f hRT
  have hXRegular : ∀ᵐ omega ∂mu,
      (∀ t, ContinuousWithinAt (X · omega) (Ici t) t) ∧
      ∀ t, Tendsto (fun s => X s omega) (nhdsWithin t (Iio t))
        (nhds (Function.leftLim (fun s => X s omega) t)) :=
    stoppedFactorialGridRightLimit_condExp_isCadlag_ae F f hRT
  obtain ⟨Y, hYAdapted, hYRight, hYLeft, hYX⟩ :=
    exists_stronglyAdapted_rightContinuous_leftLimits_version
      hUsual hXAdapted hXRegular
  have hXMartingale : Martingale X F mu :=
    stoppedFactorialGridRightLimit_condExp_martingale
      F hUsual f hRT
  have hYMartingale : Martingale Y F mu :=
    hXMartingale.congr hYAdapted fun t => (hYX.eventuallyEq_at t).symm
  exact ⟨Y, hYMartingale, hYRight, hYLeft, hYX⟩

/-- Conditional-expectation right-limit versions with different horizons
agree indistinguishably on every strictly smaller deterministic horizon. -/
theorem stoppedFactorialGridRightLimit_condExp_indistinguishable
    {mu : Measure Omega} [IsFiniteMeasure mu]
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (f : Lp Real 2 mu) {T U R : NNReal} (hRT : R < T) (hRU : R < U) :
    ProcessIndistinguishable mu
      (stoppedFactorialGridRightLimit
        (condExpMartingaleProcess mu F f) T R)
      (stoppedFactorialGridRightLimit
        (condExpMartingaleProcess mu F f) U R) := by
  let M := condExpMartingaleProcess mu F f
  have hM : Martingale M F mu :=
    martingale_condExpMartingaleProcess mu F f
  have hTerminalT : MemLp (M T) (2 : ENNReal) mu :=
    (Lp.memLp f).condExp (by norm_num)
  have hTerminalU : MemLp (M U) (2 : ENNReal) mu :=
    (Lp.memLp f).condExp (by norm_num)
  apply ProcessIndistinguishable.of_ae_eq_on_rightDense
    (stoppedFactorialGridRightLimit M T R)
    (stoppedFactorialGridRightLimit M U R)
    NNRealRightDenseSkeleton.skeleton
    NNRealRightDenseSkeleton.skeleton_rightDense
  · filter_upwards
      [Martingale.factorialGridRightLimit_isRightContinuous_ae
        hM T hTerminalT] with omega hRight
    exact continuousWithinAt_deterministicallyStopped_of_before hRT hRight
  · filter_upwards
      [Martingale.factorialGridRightLimit_isRightContinuous_ae
        hM U hTerminalU] with omega hRight
    exact continuousWithinAt_deterministicallyStopped_of_before hRU hRight
  · intro k
    let s := min (NNRealRightDenseSkeleton.skeleton k) R
    have hsT : s < T := (min_le_right _ _).trans_lt hRT
    have hsU : s < U := (min_le_right _ _).trans_lt hRU
    change factorialGridRightLimit M T s =ᵐ[mu]
      factorialGridRightLimit M U s
    exact
      (factorialGridRightLimit_condExpMartingaleProcess_ae_eq
        F hUsual f T s hsT).trans
      (factorialGridRightLimit_condExpMartingaleProcess_ae_eq
        F hUsual f U s hsU).symm

end HorizonFactorialGrid

end FTAPTheorem42
