/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/
import FTAPTheorem42.Stochastic.Martingale.Basic.CountableRangeStoppedMartingale
import FTAPTheorem42.Stochastic.Martingale.Basic.FiniteGridMartingaleProcess
import FTAPTheorem42.Stochastic.Martingale.Basic.MartingaleWeakL1Maximal
import FTAPTheorem42.Stochastic.Process.NullSetProcessRegularization
import FTAPTheorem42.Stochastic.Process.UniformLimits
import Mathlib.MeasureTheory.Function.LpSpace.Complete
import Mathlib.MeasureTheory.OuterMeasure.BorelCantelli

/-!
# Completing martingale processes from terminal `L¹` convergence

A terminal-`L¹` Cauchy sequence of right-continuous true martingales,
all constant after one deterministic horizon, admits a subsequence which
converges uniformly outside one null set.  The extraction combines Doob's
weak `L¹` maximal estimate with a geometric terminal-distance schedule and
the first Borel--Cantelli lemma.

The pathwise uniform limit is identified at each fixed time with the
conditional-expectation martingale generated by its terminal value.  This
proves the true martingale property without assuming an integrable pathwise
maximal envelope.  Usual conditions then provide an everywhere
right-continuous version.
-/

open Filter MeasureTheory Set Topology
open scoped BigOperators ENNReal MeasureTheory NNReal ProbabilityTheory

namespace FTAPTheorem42

variable {Omega : Type*} [MeasurableSpace Omega]

namespace ChronologicalGrid

/-- A terminal-`L¹` Cauchy sequence of right-continuous martingales,
all stopped at the same deterministic horizon, has a right-continuous true
martingale process limit with the Banach-space terminal limit. -/
theorem exists_rightContinuous_martingale_of_terminalL1_cauchy
    {mu : Measure Omega} [IsProbabilityMeasure mu]
    {F : Filtration NNReal (inferInstance : MeasurableSpace Omega)}
    [SigmaFiniteFiltration mu F]
    (hUsual : Filtration.UsualConditions mu F)
    (X : Nat -> Process Omega) (T : NNReal)
    (hX : forall n, Martingale (X n) F mu)
    (hXRight : forall n omega t,
      ContinuousWithinAt (X n · omega) (Ici t) t)
    (hXConstant : forall n t, T <= t -> X n t = X n T)
    (hTerminal : forall n, MemLp (X n T) 1 mu)
    (hTerminalCauchy : CauchySeq (fun n =>
      (hTerminal n).toLp (X n T))) :
    exists cutoff : Nat -> Nat, StrictMono cutoff /\
      exists Y : Process Omega,
        Martingale Y F mu /\
          (forall omega t,
            ContinuousWithinAt (Y · omega) (Ici t) t) /\
          (forall t, T <= t -> Y t =ᵐ[mu] Y T) /\
          (∀ᵐ omega ∂mu, TendstoUniformly
            (fun n t => X (cutoff n) t omega)
            (fun t => Y t omega) atTop) /\
          exists hYTerminal : MemLp (Y T) 1 mu,
            hYTerminal.toLp (Y T) =
              limUnder atTop (fun n =>
                (hTerminal n).toLp (X n T)) := by
  let terminal : Nat -> Lp Real 1 mu := fun n =>
    (hTerminal n).toLp (X n T)
  let q : Nat -> Real := fun n => ((1 : Real) / 2) ^ (n + 1)
  let qNN : Nat -> NNReal := fun n => ⟨q n, by positivity⟩
  have hSelection : forall n, exists N, forall a b,
      N <= a -> N <= b ->
      dist (terminal a) (terminal b) <
        (((qNN n / 2) * qNN n : NNReal) : Real) := by
    intro n
    have hqNNPos : 0 < qNN n := by
      change 0 < q n
      dsimp [q]
      positivity
    have hRadiusPos :
        0 < (((qNN n / 2) * qNN n : NNReal) : Real) := by
      exact_mod_cast mul_pos (div_pos hqNNPos (by norm_num)) hqNNPos
    obtain ⟨N, hN⟩ := Metric.cauchySeq_iff.mp hTerminalCauchy
      ((((qNN n / 2) * qNN n : NNReal) : Real)) hRadiusPos
    exact ⟨N, fun a b ha hb => by
      simpa only [terminal] using hN a ha b hb⟩
  choose witness hWitness using hSelection
  let cutoff : Nat -> Nat := fun n =>
    Nat.rec (witness 0)
      (fun k previous => max (previous + 1) (witness (k + 1))) n
  have hWitnessLeCutoff : forall n, witness n <= cutoff n := by
    intro n
    induction n with
    | zero => simp [cutoff]
    | succ n _ih =>
        dsimp [cutoff]
        exact le_max_right _ _
  have hCutoffStep : forall n, cutoff n < cutoff (n + 1) := by
    intro n
    dsimp [cutoff]
    exact lt_of_lt_of_le (Nat.lt_succ_self _) (le_max_left _ _)
  have hCutoff : StrictMono cutoff := strictMono_nat_of_lt_succ hCutoffStep
  let Z : Nat -> Process Omega := fun n => X (cutoff n)
  let D : Nat -> Process Omega := fun n => Z (n + 1) - Z n
  have hD : forall n, Martingale (D n) F mu := fun n =>
    (hX (cutoff (n + 1))).sub (hX (cutoff n))
  have hDRight : forall n omega t,
      ContinuousWithinAt (D n · omega) (Ici t) t := by
    intro n omega t
    exact (hXRight (cutoff (n + 1)) omega t).sub
      (hXRight (cutoff n) omega t)
  have hDConstant : forall n t, T <= t -> D n t = D n T := by
    intro n t ht
    funext omega
    simp only [D, Z, Pi.sub_apply, hXConstant _ t ht]
  have hTerminalDistance : forall n,
      eLpNorm (D n T) 1 mu = ENNReal.ofReal
        (dist (terminal (cutoff (n + 1)))
          (terminal (cutoff n))) := by
    intro n
    calc
      eLpNorm (D n T) 1 mu =
          edist (terminal (cutoff (n + 1)))
            (terminal (cutoff n)) := by
        dsimp only [D, Z, terminal]
        exact (Lp.edist_toLp_toLp
          (X (cutoff (n + 1)) T) (X (cutoff n) T)
          (hTerminal (cutoff (n + 1)))
          (hTerminal (cutoff n))).symm
      _ = ENNReal.ofReal
          (dist (terminal (cutoff (n + 1)))
            (terminal (cutoff n))) := Lp.edist_dist _ _
  have hSelectedDistance : forall n,
      dist (terminal (cutoff (n + 1)))
          (terminal (cutoff n)) <
        (((qNN n / 2) * qNN n : NNReal) : Real) := by
    intro n
    exact hWitness n (cutoff (n + 1)) (cutoff n)
      ((hWitnessLeCutoff n).trans
        (hCutoff.monotone (Nat.le_succ n)))
      (hWitnessLeCutoff n)
  let bad : Nat -> Set Omega := fun n =>
    {omega | exists t, q n <= |D n t omega|}
  have hBadMeasure : forall n,
      mu (bad n) <= ENNReal.ofReal (q n) := by
    intro n
    have hqNNPos : 0 < qNN n := by
      change 0 < q n
      dsimp [q]
      positivity
    have hqNNNe : qNN n ≠ 0 := ne_of_gt hqNNPos
    have hhalfNe : qNN n / 2 ≠ 0 :=
      div_ne_zero hqNNNe (by norm_num)
    have hWeak :=
      FactorialChronologicalGrid.Martingale.measure_exists_abs_ge_le
        (hD n) (hDRight n) T (hDConstant n)
        hqNNNe
    have hTerminalBound : eLpNorm (D n T) 1 mu <=
        (((qNN n / 2) * qNN n : NNReal) : ENNReal) := by
      rw [hTerminalDistance n]
      calc
        ENNReal.ofReal
            (dist (terminal (cutoff (n + 1)))
              (terminal (cutoff n))) <=
            ENNReal.ofReal
              ((((qNN n / 2) * qNN n : NNReal) : Real)) :=
          ENNReal.ofReal_le_ofReal (hSelectedDistance n).le
        _ = (((qNN n / 2) * qNN n : NNReal) : ENNReal) := by
          rw [ENNReal.ofReal_coe_nnreal]
    calc
      mu (bad n) <=
          ((qNN n / 2 : NNReal) : ENNReal)⁻¹ *
            eLpNorm (D n T) 1 mu := by
        change mu {omega | exists t, (qNN n : Real) <= |D n t omega|} <= _
        simpa only [bad, qNN, NNReal.coe_mk] using hWeak
      _ <= ((qNN n / 2 : NNReal) : ENNReal)⁻¹ *
          (((qNN n / 2) * qNN n : NNReal) : ENNReal) := by
        gcongr
      _ = (qNN n : ENNReal) := by
        rw [ENNReal.coe_mul]
        exact ENNReal.inv_mul_cancel_left
          (ENNReal.coe_ne_zero.mpr hhalfNe)
          ENNReal.coe_ne_top
      _ = ENNReal.ofReal (q n) := by
        exact (ENNReal.ofReal_eq_coe_nnreal (qNN n).2).symm
  have hqSummable : Summable q := by
    simpa [q, pow_succ, mul_comm] using
      (summable_geometric_two.mul_left ((1 : Real) / 2))
  have hBadSum : (∑' n, mu (bad n)) ≠ ∞ := by
    apply ne_top_of_le_ne_top hqSummable.tsum_ofReal_ne_top
    exact ENNReal.tsum_le_tsum hBadMeasure
  have hEventuallyGood : ∀ᵐ omega ∂mu, ∀ᶠ n in atTop,
      omega ∉ bad n :=
    MeasureTheory.ae_eventually_notMem (μ := mu) (s := bad) hBadSum
  have hStep : ∀ᵐ omega ∂mu, ∀ᶠ n in atTop, forall t,
      dist (Z n t omega) (Z (n + 1) t omega) <= q n := by
    filter_upwards [hEventuallyGood] with omega homega
    filter_upwards [homega] with n hn
    intro t
    have hlt : |D n t omega| < q n := by
      exact lt_of_not_ge fun hge => hn ⟨t, hge⟩
    simpa only [D, Z, Pi.sub_apply, Real.dist_eq, abs_sub_comm]
      using hlt.le
  let raw : Process Omega := fun t omega =>
    limUnder atTop (fun n => Z n t omega)
  have hRawLimit : ∀ᵐ omega ∂mu, forall t,
      Tendsto (fun n => Z n t omega) atTop (nhds (raw t omega)) := by
    filter_upwards [hStep] with omega hStepOmega
    obtain ⟨K, hK⟩ := eventually_atTop.mp hStepOmega
    intro t
    have hShiftDistance : forall n,
        dist (Z (K + n) t omega) (Z (K + n + 1) t omega) <=
          q (K + n) := by
      intro n
      exact hK (K + n) (Nat.le_add_right K n) t
    have hShiftSummable : Summable (fun n => q (K + n)) := by
      exact hqSummable.comp_injective (fun _ _ h => Nat.add_left_cancel h)
    have hShiftCauchy : CauchySeq (fun n => Z (K + n) t omega) := by
      apply cauchySeq_of_dist_le_of_summable (fun n => q (K + n))
      · simpa only [Nat.add_assoc] using hShiftDistance
      · exact hShiftSummable
    have hFullCauchy : CauchySeq (fun n => Z n t omega) := by
      rw [← cauchySeq_shift K]
      simpa only [Function.comp_def, add_comm] using hShiftCauchy
    exact hFullCauchy.tendsto_limUnder
  have hRawUniform : ∀ᵐ omega ∂mu,
      TendstoUniformly (fun n t => Z n t omega)
        (fun t => raw t omega) atTop := by
    filter_upwards [hStep, hRawLimit] with omega hStepOmega hLimitOmega
    exact tendstoUniformly_of_eventually_dist_step_le_of_summable
      (fun n t => Z n t omega) (fun t => raw t omega) q
      hqSummable (fun n => (qNN n).2) hStepOmega hLimitOmega
  have hRawRight : ∀ᵐ omega ∂mu, forall t,
      ContinuousWithinAt (raw · omega) (Ici t) t := by
    filter_upwards [hRawUniform] with omega hUniform
    exact rightContinuous_of_tendstoUniformly
      (fun n t => Z n t omega) (fun t => raw t omega)
      hUniform (fun n => hXRight (cutoff n) omega)
  have hRawAdapted : StronglyAdapted F raw := by
    intro t
    change StronglyMeasurable[F t]
      (fun omega => limUnder atTop (fun n => Z n t omega))
    exact @StronglyMeasurable.limUnder
      Nat Omega Real (F t) _ _ atTop _
      (fun n omega => Z n t omega) _ _
      (fun n => (hX (cutoff n)).stronglyMeasurable t)
  let terminalLimit : Lp Real 1 mu := limUnder atTop terminal
  have hTerminalLpLimit : Tendsto terminal atTop (nhds terminalLimit) :=
    hTerminalCauchy.tendsto_limUnder
  have hSelectedTerminalLpLimit : Tendsto
      (fun n => terminal (cutoff n)) atTop (nhds terminalLimit) :=
    hTerminalLpLimit.comp hCutoff.tendsto_atTop
  have hSelectedTerminalInMeasure : TendstoInMeasure mu
      (fun n => X (cutoff n) T) atTop (terminalLimit : Omega -> Real) := by
    apply TendstoInMeasure.congr_left
      (fun n => (hTerminal (cutoff n)).coeFn_toLp)
    exact tendstoInMeasure_of_tendsto_Lp hSelectedTerminalLpLimit
  have hRawTerminalInMeasure : TendstoInMeasure mu
      (fun n => X (cutoff n) T) atTop (raw T) := by
    apply tendstoInMeasure_of_tendsto_ae
      (fun n => ((hX (cutoff n)).stronglyMeasurable T).mono
        (F.le T) |>.aestronglyMeasurable)
    exact hRawLimit.mono fun _ homega => homega T
  have hTerminalLimitEq : (terminalLimit : Omega -> Real) =ᵐ[mu] raw T :=
    tendstoInMeasure_ae_unique hSelectedTerminalInMeasure
      hRawTerminalInMeasure
  have hRawTerminal : MemLp (raw T) 1 mu :=
    (Lp.memLp terminalLimit).ae_eq hTerminalLimitEq
  have hRawTerminalIntegrable : Integrable (raw T) mu :=
    hRawTerminal.integrable (by norm_num)
  have hRawTerminalToLp : hRawTerminal.toLp (raw T) = terminalLimit := by
    exact (MemLp.toLp_congr hRawTerminal (Lp.memLp terminalLimit)
      hTerminalLimitEq.symm).trans
        (Lp.toLp_coeFn terminalLimit (Lp.memLp terminalLimit))
  have hSelectedTerminalLpRaw : Tendsto
      (fun n => (hTerminal (cutoff n)).toLp (X (cutoff n) T))
      atTop (nhds (hRawTerminal.toLp (raw T))) := by
    simpa only [terminal, hRawTerminalToLp] using hSelectedTerminalLpLimit
  have hSelectedTerminalNorm : Tendsto (fun n =>
      eLpNorm (X (cutoff n) T - raw T) 1 mu) atTop (nhds 0) :=
    (Lp.tendsto_Lp_iff_tendsto_eLpNorm''
      (fun n => X (cutoff n) T)
      (fun n => hTerminal (cutoff n)) (raw T) hRawTerminal).mp
        hSelectedTerminalLpRaw
  let base : Process Omega := fun t => mu[raw T | F t]
  let stopped : Process Omega :=
    MeasureTheory.stoppedProcess base
      (fun _ : Omega => (T : WithTop NNReal))
  have hBase : Martingale base F mu := martingale_condExp (raw T) F mu
  have hStopped : Martingale stopped F mu := by
    exact martingale_stoppedProcess_of_countableRange hBase
      (isStoppingTime_const F T) Set.finite_range_const.countable
  have hRawEqStopped : forall t, raw t =ᵐ[mu] stopped t := by
    intro t
    by_cases ht : t <= T
    · have hAtNormLe : forall n,
          eLpNorm (X (cutoff n) t - base t) 1 mu <=
            eLpNorm (X (cutoff n) T - raw T) 1 mu := by
        intro n
        have hConditional :
            X (cutoff n) t - base t =ᵐ[mu]
              mu[X (cutoff n) T - raw T | F t] := by
          have hSub := condExp_sub (hX (cutoff n) |>.integrable T)
            hRawTerminalIntegrable (F t)
          filter_upwards [hX (cutoff n) |>.condExp_ae_eq ht, hSub]
              with omega hMartingale hSubOmega
          dsimp only [base]
          rw [hSubOmega]
          simp only [Pi.sub_apply, hMartingale]
        calc
          eLpNorm (X (cutoff n) t - base t) 1 mu =
              eLpNorm (mu[X (cutoff n) T - raw T | F t]) 1 mu :=
            eLpNorm_congr_ae hConditional
          _ <= eLpNorm (X (cutoff n) T - raw T) 1 mu :=
            eLpNorm_condExp_le_eLpNorm _ le_rfl
      have hAtNorm : Tendsto (fun n =>
          eLpNorm (X (cutoff n) t - base t) 1 mu)
          atTop (nhds 0) := by
        apply ENNReal.tendsto_nhds_zero.mpr
        intro epsilon hepsilon
        filter_upwards [ENNReal.tendsto_nhds_zero.mp
          hSelectedTerminalNorm epsilon hepsilon] with n hn
        exact (hAtNormLe n).trans hn
      have hBaseInMeasure : TendstoInMeasure mu
          (fun n => X (cutoff n) t) atTop (base t) := by
        exact tendstoInMeasure_of_tendsto_eLpNorm (p := (1 : ENNReal))
          (by norm_num)
          hAtNorm
      have hRawInMeasure : TendstoInMeasure mu
          (fun n => X (cutoff n) t) atTop (raw t) := by
        apply tendstoInMeasure_of_tendsto_ae
          (fun n => ((hX (cutoff n)).stronglyMeasurable t).mono
            (F.le t) |>.aestronglyMeasurable)
        exact hRawLimit.mono fun _ homega => homega t
      have hRawEqBase : raw t =ᵐ[mu] base t :=
        (tendstoInMeasure_ae_unique hRawInMeasure hBaseInMeasure)
      filter_upwards [hRawEqBase] with omega homega
      rw [homega]
      change base t omega = MeasureTheory.stoppedProcess base
        (fun _ : Omega => (T : WithTop NNReal)) t omega
      rw [stoppedProcess_const_apply, min_eq_left ht]
    · have hTt : T <= t := le_of_not_ge ht
      have hRawConstant : raw t = raw T := by
        funext omega
        apply congrArg (limUnder atTop)
        funext n
        exact congrFun (hXConstant (cutoff n) t hTt) omega
      have hCondTerminal : base T = raw T := by
        exact condExp_of_stronglyMeasurable (F.le T)
          (hRawAdapted T) hRawTerminalIntegrable
      rw [hRawConstant]
      exact Filter.Eventually.of_forall fun omega => by
        change raw T omega = MeasureTheory.stoppedProcess base
          (fun _ : Omega => (T : WithTop NNReal)) t omega
        rw [stoppedProcess_const_apply, min_eq_right hTt, hCondTerminal]
  have hRawMartingale : Martingale raw F mu :=
    hStopped.congr hRawAdapted fun t => (hRawEqStopped t).symm
  obtain ⟨Y, hYAdapted, hYRight, hYRaw⟩ :=
    ProcessNullSetRegularization.exists_stronglyAdapted_rightContinuous_version
      hUsual hRawAdapted hRawRight
  have hYMartingale : Martingale Y F mu :=
    hRawMartingale.congr hYAdapted
      (fun t => (hYRaw.eventuallyEq_at t).symm)
  have hYConstant : forall t, T <= t -> Y t =ᵐ[mu] Y T := by
    intro t ht
    filter_upwards [hYRaw.eventuallyEq_at t,
      hYRaw.eventuallyEq_at T] with omega hYt hYT
    rw [hYt, hYT]
    dsimp only [raw]
    apply congrArg (limUnder atTop)
    funext n
    exact congrFun (hXConstant (cutoff n) t ht) omega
  have hYTerminal : MemLp (Y T) 1 mu :=
    hRawTerminal.ae_eq (hYRaw.eventuallyEq_at T).symm
  have hYTerminalToLp : hYTerminal.toLp (Y T) =
      hRawTerminal.toLp (raw T) :=
    MemLp.toLp_congr hYTerminal hRawTerminal
      (hYRaw.eventuallyEq_at T)
  have hYUniform : ∀ᵐ omega ∂mu,
      TendstoUniformly (fun n t => X (cutoff n) t omega)
        (fun t => Y t omega) atTop := by
    filter_upwards [hRawUniform, hYRaw] with omega hUniform hEq
    have hPathEq : (fun t => Y t omega) = fun t => raw t omega := by
      funext t
      exact hEq t
    rw [hPathEq]
    simpa only [Z] using hUniform
  refine ⟨cutoff, hCutoff, Y, hYMartingale, hYRight,
    hYConstant, hYUniform, hYTerminal, ?_⟩
  exact hYTerminalToLp.trans hRawTerminalToLp

end ChronologicalGrid

end FTAPTheorem42
