/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/
import FTAPTheorem42.Stochastic.Topology.Emery.PositiveScalar
import FTAPTheorem42.Stochastic.Integral.Calculus.SemimartingaleStrategy

/-!
# A candidate-specific terminal carrier for the realized Emery market

The realized Emery carrier deliberately has no terminal value.  A terminal
strategy is therefore a subcarrier: it carries one realized strategy together
with a terminal representative and an almost-sure limit witness for that
particular gain process.  This module supplies the corresponding concrete
`GainProcessModel` and the elementary `K₁` candidate consumer.

No terminal convergence is asserted for the whole realized carrier, and no
component decomposition or final realization witness is stored here.
-/

open Filter MeasureTheory Set Topology
open scoped ENNReal NNReal ProbabilityTheory

namespace FTAPTheorem42

variable {Ω : Type*} [MeasurableSpace Ω]

namespace PredictableElementaryEmery

variable {ℱ : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)}

/-- A realized Emery strategy equipped with one candidate-specific terminal
representative and its almost-sure continuous-time limit witness. -/
structure TerminalStrategy
    (μ : Measure Ω) (S : Process Ω) where
  realized : RealizedStrategy (ℱ := ℱ) μ S
  terminalGain : Ω → ℝ
  terminalWitness : ∀ᵐ ω ∂μ,
    Tendsto (fun t : ℝ≥0 => realized.gain t ω) atTop
      (𝓝 (terminalGain ω))

namespace TerminalStrategy

/-- Replace only the terminal representative by an a.e.-equal function. -/
def replaceTerminalGain
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {S : Process Ω}
    (H : TerminalStrategy (ℱ := ℱ) μ S)
    (g : Ω → ℝ)
    (hEq : H.terminalGain =ᵐ[μ] g) :
    TerminalStrategy (ℱ := ℱ) μ S where
  realized := H.realized
  terminalGain := g
  terminalWitness := by
    filter_upwards [H.terminalWitness, hEq] with ω hTerminal hOmega
    rwa [← hOmega]

/-- The canonical terminal zero in the candidate-specific subcarrier. -/
noncomputable def zero
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (S : Process Ω)
    (hS : IsStronglyProgressive ℱ S) :
    TerminalStrategy (ℱ := ℱ) μ S where
  realized := RealizedStrategy.zero S hS
  terminalGain := fun _ => 0
  terminalWitness := by
    filter_upwards [] with ω
    change Tendsto (fun _ : ℝ≥0 => (0 : ℝ)) atTop (𝓝 0)
    exact tendsto_const_nhds

/-- Addition preserves the candidate-specific terminal witness. -/
noncomputable def add
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (S : Process Ω)
    (hS : IsStronglyProgressive ℱ S)
    (H K : TerminalStrategy (ℱ := ℱ) μ S) :
    TerminalStrategy (ℱ := ℱ) μ S where
  realized := H.realized.add S hS K.realized
  terminalGain := fun ω => H.terminalGain ω + K.terminalGain ω
  terminalWitness := by
    filter_upwards [H.terminalWitness, K.terminalWitness]
      with ω hH hK
    exact hH.add hK

/-- Positive scalar multiplication preserves the candidate-specific terminal
limit witness. -/
noncomputable def posSMul
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (S : Process Ω)
    (hS : IsStronglyProgressive ℱ S)
    (H : TerminalStrategy (ℱ := ℱ) μ S)
    (c : ℝ) (hc : 0 < c) :
    TerminalStrategy (ℱ := ℱ) μ S where
  realized := H.realized.posSMul S hS c hc
  terminalGain := fun ω => c * H.terminalGain ω
  terminalWitness := by
    filter_upwards [H.terminalWitness] with ω hOmega
    exact hOmega.const_mul c

end TerminalStrategy

/-- The gain-process model generated by the candidate-specific terminal
subcarrier of the realized Emery market. -/
noncomputable def terminalGainProcessModel
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (S : Process Ω)
    (hS : IsStronglyProgressive ℱ S) :
    GainProcessModel Ω ℝ≥0 where
  Strategy := TerminalStrategy (ℱ := ℱ) μ S
  gain := fun H => H.realized.gain
  terminalGain := fun H => H.terminalGain
  zeroStrategy := TerminalStrategy.zero S hS
  addStrategy := TerminalStrategy.add S hS
  posSMulStrategy := fun c hc H => TerminalStrategy.posSMul S hS H c hc
  gain_zero := by
    intro t
    rfl
  gain_add := by
    intro H K t
    rfl
  gain_posSMul := by
    intro c hc H t
    rfl
  terminalGain_zero := by
    rfl
  terminalGain_add := by
    intro H K
    rfl
  terminalGain_posSMul := by
    intro c hc H
    rfl

namespace TerminalStrategy

/-- The terminal claim is a.e. strongly measurable.  This is obtained from
the strongly adapted running gain and the a.s. terminal witness, via the
generic terminal-measurability bridge. -/
theorem terminalGain_aestronglyMeasurable
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (S : Process Ω)
    (hS : IsStronglyProgressive ℱ S)
    (H : TerminalStrategy (ℱ := ℱ) μ S) :
    AEStronglyMeasurable H.terminalGain μ := by
  let A := terminalGainProcessModel (ℱ := ℱ) S hS (μ := μ)
  have hAdapted : StronglyAdapted ℱ (A.gain H) := by
    intro t
    exact H.realized.gain_stronglyAdapted t
  have hTerminal : ∀ᵐ ω ∂μ,
      Tendsto (fun t : ℝ≥0 => A.gain H t ω) atTop
        (𝓝 (A.terminalGain H ω)) := by
    exact H.terminalWitness
  exact A.terminalGain_aestronglyMeasurable_of_adapted_tendsto
    H hAdapted hTerminal

end TerminalStrategy

/-- Every admissible terminal claim in the Emery terminal model is a.e.
strongly measurable. -/
theorem terminalGainProcessModel_K0_aestronglyMeasurable
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (S : Process Ω)
    (hS : IsStronglyProgressive ℱ S) :
    ClaimSetAEStronglyMeasurable μ
      ((terminalGainProcessModel (ℱ := ℱ) S hS (μ := μ)).K0OfGainProcessModel μ) := by
  rintro f ⟨H, _hAdmissible, rfl⟩
  exact H.terminalGain_aestronglyMeasurable S hS

/-- Running admissibility lower bounds pass to the candidate-specific terminal
limit.  Only integer times are intersected, so no uncountable-time null-set
intersection is used. -/
theorem terminalGainProcessModel_terminalGainRespectsAdmissibleLowerBound
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (S : Process Ω)
    (hS : IsStronglyProgressive ℱ S) :
    (terminalGainProcessModel
      (ℱ := ℱ) S hS (μ := μ)).TerminalGainRespectsAdmissibleLowerBound μ := by
  intro H a _ha hRunning
  have hInteger : ∀ᵐ ω ∂μ, ∀ n : Nat,
      -a ≤ H.realized.gain (n : ℝ≥0) ω :=
    ae_all_iff.mpr fun n => hRunning (n : ℝ≥0)
  filter_upwards [hInteger, H.terminalWitness]
    with ω hLower hTerminal
  have hTerminalInteger : Tendsto
      (fun n : Nat => H.realized.gain (n : ℝ≥0) ω)
      atTop (𝓝 (H.terminalGain ω)) :=
    hTerminal.comp tendsto_natCast_atTop_atTop
  exact ge_of_tendsto' hTerminalInteger hLower

end PredictableElementaryEmery

end FTAPTheorem42
