import FTAPTheorem42.Trading.Closure

/-!
# Gain-process trading models

This file isolates the admissibility interface used in Delbaen--Schachermayer:
an admissible strategy is one whose running gains are bounded below a.e. by a
finite constant.  The interface is deliberately abstract, so it can be
instantiated by discrete models or by continuous-time stochastic integrals.
-/

open Filter MeasureTheory

namespace FTAPTheorem42

variable {Ω : Type*} [MeasurableSpace Ω]

/--
A trading model with a running gain process and a terminal gain.  The time index
is abstract so that finite-horizon discrete models and continuous-time
stochastic-integral models can use the same admissibility definition.
-/
structure GainProcessModel (Ω : Type*) [MeasurableSpace Ω] (Time : Type*) where
  Strategy : Type*
  gain : Strategy → Time → Ω → ℝ
  terminalGain : Strategy → Ω → ℝ
  zeroStrategy : Strategy
  addStrategy : Strategy → Strategy → Strategy
  posSMulStrategy : (c : ℝ) → 0 < c → Strategy → Strategy
  gain_zero : ∀ t, gain zeroStrategy t = fun _ => 0
  gain_add :
    ∀ ⦃H G : Strategy⦄ t,
      gain (addStrategy H G) t = fun ω => gain H t ω + gain G t ω
  gain_posSMul :
    ∀ ⦃c : ℝ⦄, (hc : 0 < c) → ∀ ⦃H : Strategy⦄ t,
      gain (posSMulStrategy c hc H) t = fun ω => c * gain H t ω
  terminalGain_zero : terminalGain zeroStrategy = fun _ => 0
  terminalGain_add :
    ∀ ⦃H G : Strategy⦄,
      terminalGain (addStrategy H G) = fun ω => terminalGain H ω + terminalGain G ω
  terminalGain_posSMul :
    ∀ ⦃c : ℝ⦄, (hc : 0 < c) → ∀ ⦃H : Strategy⦄,
      terminalGain (posSMulStrategy c hc H) = fun ω => c * terminalGain H ω

namespace GainProcessModel

/-- DS-style admissibility: running gains are a.e. bounded below by `-a`. -/
def Admissible {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) (H : A.Strategy) : Prop :=
  ∃ a : ℝ, 0 < a ∧ ∀ t : Time, AELowerBoundedBy μ (-a) (A.gain H t)

/-- Fixed-level admissibility: running gains are a.e. bounded below by `-a`. -/
def AdmissibleBy {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) (a : ℝ)
    (H : A.Strategy) : Prop :=
  0 < a ∧ ∀ t : Time, AELowerBoundedBy μ (-a) (A.gain H t)

/-- The class of `1`-admissible strategies. -/
def OneAdmissible {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) (H : A.Strategy) : Prop :=
  A.AdmissibleBy μ 1 H

theorem admissibleBy_admissible {Time : Type*}
    (A : GainProcessModel Ω Time) {μ : Measure Ω} {a : ℝ} {H : A.Strategy}
    (hH : A.AdmissibleBy μ a H) :
    A.Admissible μ H :=
  ⟨a, hH.1, hH.2⟩

theorem oneAdmissible_admissible {Time : Type*}
    (A : GainProcessModel Ω Time) {μ : Measure Ω} {H : A.Strategy}
    (hH : A.OneAdmissible μ H) :
    A.Admissible μ H :=
  A.admissibleBy_admissible hH

/-- Terminal gains generated by strategies satisfying a predicate. -/
def TerminalGainsOf {Time : Type*}
    (A : GainProcessModel Ω Time) (_μ : Measure Ω)
    (P : A.Strategy → Prop) : Set (Ω → ℝ) :=
  { f | ∃ H, P H ∧ A.terminalGain H = f }

/-- Terminal gains generated by admissible strategies. -/
def K0OfGainProcessModel {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) : Set (Ω → ℝ) :=
  A.TerminalGainsOf μ (A.Admissible μ)

/-- Terminal gains generated by `1`-admissible strategies. -/
def K1OfGainProcessModel {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) : Set (Ω → ℝ) :=
  A.TerminalGainsOf μ (A.OneAdmissible μ)

theorem K1_subset_K0OfGainProcessModel {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) :
    A.K1OfGainProcessModel μ ⊆ A.K0OfGainProcessModel μ := by
  rintro f ⟨H, hH, hHgain⟩
  exact ⟨H, A.oneAdmissible_admissible hH, hHgain⟩

/-- Terminal-gain lower bounds are inherited from the running gain process. -/
def TerminalGainRespectsAdmissibleLowerBound {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) : Prop :=
  ∀ ⦃H : A.Strategy⦄ ⦃a : ℝ⦄,
    0 < a →
      (∀ t : Time, AELowerBoundedBy μ (-a) (A.gain H t)) →
        AELowerBoundedBy μ (-a) (A.terminalGain H)

/--
Terminal lower bounds control the whole gain process.  This is the abstract
boundary corresponding to the DS estimate that lets a terminal `-1` lower bound
promote an admissible strategy to `1`-admissible.
-/
def TerminalLowerBoundControlsGain {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) : Prop :=
  ∀ ⦃H : A.Strategy⦄ ⦃a : ℝ⦄,
    0 < a →
      A.Admissible μ H →
        AELowerBoundedBy μ (-a) (A.terminalGain H) →
          ∀ t : Time, AELowerBoundedBy μ (-a) (A.gain H t)

theorem K1_subset_ClaimSetWithAELowerBound {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω)
    (hTerminal : A.TerminalGainRespectsAdmissibleLowerBound μ) :
    A.K1OfGainProcessModel μ ⊆
      ClaimSetWithAELowerBound μ 1 (A.K0OfGainProcessModel μ) := by
  rintro f ⟨H, hH, hHgain⟩
  refine ⟨⟨H, A.oneAdmissible_admissible hH, hHgain⟩, ?_⟩
  have hterm : AELowerBoundedBy μ (-1) (A.terminalGain H) :=
    hTerminal hH.1 hH.2
  simpa [hHgain] using hterm

theorem admissible_zero {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) :
    A.Admissible μ A.zeroStrategy := by
  refine ⟨1, zero_lt_one, ?_⟩
  intro t
  rw [A.gain_zero t]
  exact Filter.Eventually.of_forall (fun _ => by norm_num)

theorem admissible_add {Time : Type*}
    (A : GainProcessModel Ω Time) {μ : Measure Ω}
    {H G : A.Strategy}
    (hH : A.Admissible μ H) (hG : A.Admissible μ G) :
    A.Admissible μ (A.addStrategy H G) := by
  rcases hH with ⟨a, ha, hHa⟩
  rcases hG with ⟨b, hb, hGb⟩
  refine ⟨a + b, add_pos ha hb, ?_⟩
  intro t
  rw [A.gain_add t]
  filter_upwards [hHa t, hGb t] with ω hHω hGω
  linarith

theorem admissible_posSMul {Time : Type*}
    (A : GainProcessModel Ω Time) {μ : Measure Ω}
    {c : ℝ} (hc : 0 < c) {H : A.Strategy}
    (hH : A.Admissible μ H) :
    A.Admissible μ (A.posSMulStrategy c hc H) := by
  rcases hH with ⟨a, ha, hHa⟩
  refine ⟨c * a, mul_pos hc ha, ?_⟩
  intro t
  rw [A.gain_posSMul hc t]
  filter_upwards [hHa t] with ω hHω
  nlinarith [mul_pos hc ha]

/--
Nonnegative scalar multiplication of strategies.  The primitive model only
contains strictly positive scalar multiplication, so the zero scalar is routed
through the zero strategy.
-/
noncomputable def nonnegSMulStrategy {Time : Type*}
    (A : GainProcessModel Ω Time) (c : ℝ) (H : A.Strategy) : A.Strategy :=
  if hc : 0 < c then A.posSMulStrategy c hc H else A.zeroStrategy

theorem gain_nonnegSMulStrategy {Time : Type*}
    (A : GainProcessModel Ω Time) {c : ℝ} (hc : 0 ≤ c)
    (H : A.Strategy) (t : Time) :
    A.gain (A.nonnegSMulStrategy c H) t =
      fun ω => c * A.gain H t ω := by
  by_cases hpos : 0 < c
  · simp [nonnegSMulStrategy, hpos, A.gain_posSMul hpos]
  · have hzero : c = 0 := le_antisymm (le_of_not_gt hpos) hc
    simp [nonnegSMulStrategy, hzero, A.gain_zero]

theorem terminalGain_nonnegSMulStrategy {Time : Type*}
    (A : GainProcessModel Ω Time) {c : ℝ} (hc : 0 ≤ c)
    (H : A.Strategy) :
    A.terminalGain (A.nonnegSMulStrategy c H) =
      fun ω => c * A.terminalGain H ω := by
  by_cases hpos : 0 < c
  · simp [nonnegSMulStrategy, hpos, A.terminalGain_posSMul hpos]
  · have hzero : c = 0 := le_antisymm (le_of_not_gt hpos) hc
    simp [nonnegSMulStrategy, hzero, A.terminalGain_zero]

theorem oneAdmissible_convexCombo {Time : Type*}
    (A : GainProcessModel Ω Time) {μ : Measure Ω}
    {a b : ℝ} (ha : 0 ≤ a) (hb : 0 ≤ b) (hsum : a + b = 1)
    {H G : A.Strategy}
    (hH : A.OneAdmissible μ H) (hG : A.OneAdmissible μ G) :
    A.OneAdmissible μ
      (A.addStrategy (A.nonnegSMulStrategy a H)
        (A.nonnegSMulStrategy b G)) := by
  refine ⟨zero_lt_one, ?_⟩
  intro t
  rw [A.gain_add t, A.gain_nonnegSMulStrategy ha H t,
    A.gain_nonnegSMulStrategy hb G t]
  filter_upwards [hH.2 t, hG.2 t] with ω hHω hGω
  calc
    (-1 : ℝ)
        = a * (-1) + b * (-1) := by rw [← add_mul, hsum, one_mul]
    _ ≤ a * A.gain H t ω + b * A.gain G t ω := by
        exact add_le_add
          (mul_le_mul_of_nonneg_left hHω ha)
          (mul_le_mul_of_nonneg_left hGω hb)

theorem terminalGain_convexCombo {Time : Type*}
    (A : GainProcessModel Ω Time)
    {a b : ℝ} (ha : 0 ≤ a) (hb : 0 ≤ b)
    (H G : A.Strategy) :
    A.terminalGain
      (A.addStrategy (A.nonnegSMulStrategy a H)
        (A.nonnegSMulStrategy b G)) =
      fun ω => a * A.terminalGain H ω + b * A.terminalGain G ω := by
  rw [A.terminalGain_add, A.terminalGain_nonnegSMulStrategy ha H,
    A.terminalGain_nonnegSMulStrategy hb G]

theorem K1_convexInvariant {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) :
    ConvexInvariant (A.K1OfGainProcessModel μ) := by
  intro a b ha hb hsum f g hf hg
  rcases hf with ⟨H, hH, hHterm⟩
  rcases hg with ⟨G, hG, hGterm⟩
  refine ⟨A.addStrategy (A.nonnegSMulStrategy a H)
      (A.nonnegSMulStrategy b G), ?_, ?_⟩
  · exact A.oneAdmissible_convexCombo ha hb hsum hH hG
  · rw [A.terminalGain_convexCombo ha hb H G, hHterm, hGterm]

theorem K1_apply_forwardConvexWeights_mem {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω)
    (W : ForwardConvexWeights) {G : ℕ → Ω → ℝ}
    (hG : ∀ n, G n ∈ A.K1OfGainProcessModel μ) (n : ℕ) :
    W.apply G n ∈ A.K1OfGainProcessModel μ :=
  W.apply_mem_of_convexInvariant (A.K1_convexInvariant μ) hG n

/--
The terminal-gain cone generated by gain-process-admissible strategies.
-/
def terminalGainModel {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) : TerminalGainModel Ω where
  Strategy := A.Strategy
  terminalGain := A.terminalGain
  admissible := A.Admissible μ
  zeroStrategy := A.zeroStrategy
  addStrategy := A.addStrategy
  posSMulStrategy := A.posSMulStrategy
  admissible_zero := A.admissible_zero μ
  admissible_add := by
    intro H G hH hG
    exact A.admissible_add hH hG
  admissible_posSMul := by
    intro c hc H hH
    exact A.admissible_posSMul hc hH
  terminalGain_zero := A.terminalGain_zero
  terminalGain_add := by intro H G; exact A.terminalGain_add (H := H) (G := G)
  terminalGain_posSMul := by intro c hc H; exact A.terminalGain_posSMul hc (H := H)

theorem K0_terminalGainModel_claimCone {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) :
    ClaimCone (K0OfTerminalGainModel (A.terminalGainModel μ)) :=
  K0OfTerminalGainModel_claimCone (A.terminalGainModel μ)

theorem K0OfGainProcessModel_eq_terminalGainModel {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) :
    A.K0OfGainProcessModel μ =
      K0OfTerminalGainModel (A.terminalGainModel μ) :=
  rfl

theorem K1_subset_ClaimSetWithAELowerBound_terminalGainModel {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω)
    (hTerminal : A.TerminalGainRespectsAdmissibleLowerBound μ) :
    A.K1OfGainProcessModel μ ⊆
      ClaimSetWithAELowerBound μ 1
        (K0OfTerminalGainModel (A.terminalGainModel μ)) := by
  simpa [A.K0OfGainProcessModel_eq_terminalGainModel μ] using
    A.K1_subset_ClaimSetWithAELowerBound μ hTerminal

theorem claimSetBoundedInProbability_K1_of_proposition31 {Time : Type*}
    (A : GainProcessModel Ω Time) (μ : Measure Ω) [IsFiniteMeasure μ]
    (hKmeas :
      ClaimSetStronglyMeasurable
        (K0OfTerminalGainModel (A.terminalGainModel μ)))
    (hTerminal : A.TerminalGainRespectsAdmissibleLowerBound μ)
    (hNFLVR :
      LinftyNFLVR μ
        (LinftyClaims μ
          (C0AsDifference μ
            (K0OfTerminalGainModel (A.terminalGainModel μ))))) :
    ClaimSetBoundedInProbability μ (A.K1OfGainProcessModel μ) :=
  claimSetBoundedInProbability_of_NFLVR_generalFinite_subsetLowerBound
    (K0_terminalGainModel_claimCone A μ) hKmeas
    (A.K1_subset_ClaimSetWithAELowerBound_terminalGainModel μ hTerminal)
    hNFLVR

theorem claimSetBoundedInProbability_K1_of_proposition31_aestronglyMeasurable
    {Time : Type*} (A : GainProcessModel Ω Time) (μ : Measure Ω)
    [IsFiniteMeasure μ]
    (hKmeas : ClaimSetAEStronglyMeasurable μ
      (K0OfTerminalGainModel (A.terminalGainModel μ)))
    (hTerminal : A.TerminalGainRespectsAdmissibleLowerBound μ)
    (hNFLVR : LinftyNFLVR μ
      (LinftyClaims μ
        (C0AsDifference μ
          (K0OfTerminalGainModel (A.terminalGainModel μ))))) :
    ClaimSetBoundedInProbability μ (A.K1OfGainProcessModel μ) :=
  (proposition31_generalFinite_aestronglyMeasurable
    (K0_terminalGainModel_claimCone A μ) hKmeas hNFLVR).mono
      (A.K1_subset_ClaimSetWithAELowerBound_terminalGainModel μ hTerminal)

/--
This concrete finite-measure candidate route uses the positive-tail extraction
directly.  Unlike the preceding abstract theorem, it does not take a
`KomlosExtractionForBoundedInProbability` hypothesis: Proposition 3.1 supplies
set-level boundedness, and the lower-bounded convex-set bridge performs the
selected-sequence extraction.
-/
theorem terminalGainHasAEForwardConvexCandidate_K1_of_proposition31_generalFinite
    {Time : Type*} (A : GainProcessModel Ω Time) (μ : Measure Ω)
    [IsFiniteMeasure μ]
    (hKmeas :
      ClaimSetStronglyMeasurable
        (K0OfTerminalGainModel (A.terminalGainModel μ)))
    (hTerminal : A.TerminalGainRespectsAdmissibleLowerBound μ)
    (hNFLVR :
      LinftyNFLVR μ
        (LinftyClaims μ
          (C0AsDifference μ
            (K0OfTerminalGainModel (A.terminalGainModel μ))))) :
    TerminalGainHasAEForwardConvexCandidate μ (A.K1OfGainProcessModel μ) := by
  intro G hG
  have hG_meas : ∀ n, StronglyMeasurable (G n) := by
    intro n
    apply hKmeas
    exact (A.K1_subset_K0OfGainProcessModel μ) (hG n)
  have hG_lower : ∀ n, AELowerBoundedBy μ (-1) (G n) := by
    intro n
    exact
      ((A.K1_subset_ClaimSetWithAELowerBound_terminalGainModel
        μ hTerminal) (hG n)).2
  have hD_bounded :
      ClaimSetBoundedInProbability μ (A.K1OfGainProcessModel μ) :=
    A.claimSetBoundedInProbability_K1_of_proposition31
      μ hKmeas hTerminal hNFLVR
  exact
    hasForwardConvexAELimit_of_lowerBounded_convexSet
      (μ := μ) (G := G) (D := A.K1OfGainProcessModel μ) (a := 1)
      hG_meas hG_lower (A.K1_convexInvariant μ)
      hD_bounded hG

/-- The finite-measure forward-convex candidate route for raw terminal claims.
It is invariant under changes on null sets and therefore requires only a.e.
strong measurability, together with a.e. saturation of `K1`. -/
theorem terminalGainHasAEForwardConvexCandidate_K1_of_proposition31_generalFinite_ae
    {Time : Type*} (A : GainProcessModel Ω Time) (μ : Measure Ω)
    [IsFiniteMeasure μ]
    (hKmeas : ClaimSetAEStronglyMeasurable μ
      (K0OfTerminalGainModel (A.terminalGainModel μ)))
    (hK1Saturated : AESaturated μ (A.K1OfGainProcessModel μ))
    (hTerminal : A.TerminalGainRespectsAdmissibleLowerBound μ)
    (hNFLVR : LinftyNFLVR μ
      (LinftyClaims μ
        (C0AsDifference μ
          (K0OfTerminalGainModel (A.terminalGainModel μ))))) :
    TerminalGainHasAEForwardConvexCandidate μ
      (A.K1OfGainProcessModel μ) := by
  intro G hG
  have hG_meas : ∀ n, AEStronglyMeasurable (G n) μ := fun n =>
    hKmeas (G n) (A.K1_subset_K0OfGainProcessModel μ (hG n))
  have hG_lower : ∀ n, AELowerBoundedBy μ (-1) (G n) := fun n =>
    ((A.K1_subset_ClaimSetWithAELowerBound_terminalGainModel
      μ hTerminal) (hG n)).2
  have hD_bounded :
      ClaimSetBoundedInProbability μ (A.K1OfGainProcessModel μ) :=
    A.claimSetBoundedInProbability_K1_of_proposition31_aestronglyMeasurable
      μ hKmeas hTerminal hNFLVR
  exact hasForwardConvexAELimit_of_lowerBounded_convexSet_aestronglyMeasurable
    hG_meas hG_lower (A.K1_convexInvariant μ) hD_bounded
      hK1Saturated hG

theorem fatouUpperBoundsReducible_K1_of_terminalLowerBoundControlsGain
    {Time : Type*} (A : GainProcessModel Ω Time) (μ : Measure Ω)
    (hControl : A.TerminalLowerBoundControlsGain μ) :
    FatouUpperBoundsReducible μ
      (K0OfTerminalGainModel (A.terminalGainModel μ))
      (A.K1OfGainProcessModel μ) := by
  intro f G hG hdom hlower
  classical
  choose H hHadm hHgain using hG
  refine ⟨G, ?_, hdom⟩
  intro n
  refine ⟨H n, ?_, hHgain n⟩
  refine ⟨zero_lt_one, ?_⟩
  apply hControl zero_lt_one (hHadm n)
  have htermG : AELowerBoundedBy μ (-1) (G n) := by
    filter_upwards [hlower n, hdom n] with ω hf hfg
    exact le_trans hf hfg
  have hHgain' : A.terminalGain (H n) = G n := by
    simpa [terminalGainModel] using hHgain n
  rw [hHgain']
  exact htermG

theorem terminalGainFatouStable_K0_of_K1_maximalInMeasureClosureAERealizable
    {Time : Type*} (A : GainProcessModel Ω Time) (μ : Measure Ω)
    [IsFiniteMeasure μ]
    (hKmeas :
      ClaimSetStronglyMeasurable
        (K0OfTerminalGainModel (A.terminalGainModel μ)))
    (hTerminal : A.TerminalGainRespectsAdmissibleLowerBound μ)
    (hControl : A.TerminalLowerBoundControlsGain μ)
    (hNFLVR :
      LinftyNFLVR μ
        (LinftyClaims μ
          (C0AsDifference μ
            (K0OfTerminalGainModel (A.terminalGainModel μ)))))
    (hRealize :
      MaximalInMeasureClosureAERealizableBetween μ
        (A.K1OfGainProcessModel μ)
        (K0OfTerminalGainModel (A.terminalGainModel μ))) :
    TerminalGainFatouStable μ (K0OfTerminalGainModel (A.terminalGainModel μ)) := by
  have hK1_meas_strong :
      ClaimSetStronglyMeasurable (A.K1OfGainProcessModel μ) := by
    intro f hf
    exact hKmeas f ((A.K1_subset_K0OfGainProcessModel μ) hf)
  have hK1_meas :
      ClaimSetAEStronglyMeasurable μ (A.K1OfGainProcessModel μ) :=
    hK1_meas_strong.aestronglyMeasurable
  have hK1_bounded :
      ClaimSetBoundedInProbability μ (A.K1OfGainProcessModel μ) :=
    A.claimSetBoundedInProbability_K1_of_proposition31
      μ hKmeas hTerminal hNFLVR
  have hCandidate :
      TerminalGainHasAEForwardConvexCandidate μ (A.K1OfGainProcessModel μ) :=
    A.terminalGainHasAEForwardConvexCandidate_K1_of_proposition31_generalFinite
      μ hKmeas hTerminal hNFLVR
  have hReduce :
      FatouUpperBoundsReducible μ
        (K0OfTerminalGainModel (A.terminalGainModel μ))
        (A.K1OfGainProcessModel μ) :=
    A.fatouUpperBoundsReducible_K1_of_terminalLowerBoundControlsGain μ hControl
  have hDominated :
      ForwardConvexLimitAEDominatedBetween μ
        (A.K1OfGainProcessModel μ)
        (K0OfTerminalGainModel (A.terminalGainModel μ)) :=
    forwardConvexLimitAEDominatedBetween_of_maximalInMeasureClosureAERealizable
      (A.K1_convexInvariant μ) hK1_meas hK1_bounded hRealize
  exact TerminalGainFatouStable.of_reducible_candidate_dominatedBetween
    hReduce hCandidate hDominated

end GainProcessModel

end FTAPTheorem42
