/-
Copyright (c) 2026 selpo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: selpo
-/
import FTAPTheorem42.Trading.FatouCriterion
import FTAPTheorem42.Core.WeakStarFatouClosed

/-!
# Concrete Theorem 4.2 assembly

This module assembles the closure, NFLVR, and abstract terminal-gain hypotheses
into the concrete Theorem 4.2 statements.
-/

open Filter MeasureTheory
open scoped BigOperators

namespace FTAPTheorem42

variable {Ω : Type*} [MeasurableSpace Ω]

/--
The two Theorem 4.2 conclusions for a terminal-gain cone, using the
`LinftyWeakStar` topology induced by the `L¹` integral pairing.
-/
def theorem42ConcreteWeakStarStatement
    (μ : Measure Ω) (K0 : Set (Ω → ℝ))
    (boundedSemimartingale NFLVR : Prop) : Prop :=
  boundedSemimartingale →
    NFLVR →
      FatouClosed μ (C0AsDifference μ K0) ∧
        LinftyWeakStarClosed μ (C0AsDifference μ K0)

/--
Concrete weak-star assembly from the explicit Fatou/solid/cone criterion.
The input `hCriterion` is the `σ(L∞, L¹)` functional-analytic bridge,
provided by the Krein–Šmulian argument in the theorem below.
-/
theorem theorem42ConcreteWeakStar_from_fatou_and_criterion
    (μ : Measure Ω) (K0 : Set (Ω → ℝ))
    (boundedSemimartingale NFLVR : Prop)
    (hK : ClaimCone K0)
    (hFatou :
      boundedSemimartingale →
        NFLVR →
          FatouClosed μ (C0AsDifference μ K0))
    (hCriterion :
      LinftyWeakStarClosedFromFatouCone μ (C0AsDifference μ K0)) :
    theorem42ConcreteWeakStarStatement μ K0 boundedSemimartingale NFLVR := by
  intro hS hNFLVR
  have hFatouC0 := hFatou hS hNFLVR
  have hConeC0 : ClaimCone (C0AsDifference μ K0) :=
    C0AsDifference_claimCone (μ := μ) hK
  have hSolidC0 : Solid μ (C0AsDifference μ K0) :=
    C0AsDifference_solid μ K0
  exact ⟨hFatouC0,
    linftyWeakStarClosed_of_fatouCone_criterion
      hCriterion hFatouC0 hConeC0 hSolidC0⟩

/--
Concrete weak-star assembly from Fatou closedness alone.  The
Fatou/solid/cone-to-weak-star implication is discharged by the
Krein--Šmulian theorem proved in `Core.WeakStarFatouClosed`.
-/
theorem theorem42ConcreteWeakStar_from_fatou
    (μ : Measure Ω) [IsFiniteMeasure μ]
    (K0 : Set (Ω → ℝ))
    (boundedSemimartingale NFLVR : Prop)
    (hK : ClaimCone K0)
    (hFatou :
      boundedSemimartingale →
        NFLVR →
          FatouClosed μ (C0AsDifference μ K0)) :
    theorem42ConcreteWeakStarStatement μ K0
      boundedSemimartingale NFLVR :=
  theorem42ConcreteWeakStar_from_fatou_and_criterion
    μ K0 boundedSemimartingale NFLVR hK hFatou
    (linftyWeakStarClosedFromFatouCone_impl μ
      (C0AsDifference μ K0))

/--
Abstract terminal-gain model for admissible trading strategies.  Later files can
instantiate this with predictable integrands and stochastic integrals.
-/
structure TerminalGainModel (Ω : Type*) where
  Strategy : Type*
  terminalGain : Strategy → Ω → ℝ
  admissible : Strategy → Prop
  zeroStrategy : Strategy
  addStrategy : Strategy → Strategy → Strategy
  posSMulStrategy : (c : ℝ) → 0 < c → Strategy → Strategy
  admissible_zero : admissible zeroStrategy
  admissible_add :
    ∀ ⦃H G : Strategy⦄, admissible H → admissible G → admissible (addStrategy H G)
  admissible_posSMul :
    ∀ ⦃c : ℝ⦄, (hc : 0 < c) → ∀ ⦃H : Strategy⦄,
      admissible H → admissible (posSMulStrategy c hc H)
  terminalGain_zero : terminalGain zeroStrategy = fun _ => 0
  terminalGain_add :
    ∀ ⦃H G : Strategy⦄,
      terminalGain (addStrategy H G) = fun ω => terminalGain H ω + terminalGain G ω
  terminalGain_posSMul :
    ∀ ⦃c : ℝ⦄, (hc : 0 < c) → ∀ ⦃H : Strategy⦄,
      terminalGain (posSMulStrategy c hc H) = fun ω => c * terminalGain H ω

/-- Terminal gains generated by admissible strategies in an abstract model. -/
def K0OfTerminalGainModel (A : TerminalGainModel Ω) : Set (Ω → ℝ) :=
  { f | ∃ H, A.admissible H ∧ A.terminalGain H = f }

omit [MeasurableSpace Ω] in
theorem K0OfTerminalGainModel_hasZeroClaim
    (A : TerminalGainModel Ω) :
    HasZeroClaim (K0OfTerminalGainModel A) := by
  exact ⟨A.zeroStrategy, A.admissible_zero, A.terminalGain_zero⟩

omit [MeasurableSpace Ω] in
theorem K0OfTerminalGainModel_addInvariant
    (A : TerminalGainModel Ω) :
    AddInvariant (K0OfTerminalGainModel A) := by
  intro f g hf hg
  rcases hf with ⟨H, hHadm, hHgain⟩
  rcases hg with ⟨G, hGadm, hGgain⟩
  refine ⟨A.addStrategy H G, A.admissible_add hHadm hGadm, ?_⟩
  rw [A.terminalGain_add, hHgain, hGgain]

omit [MeasurableSpace Ω] in
theorem K0OfTerminalGainModel_posSMulInvariant
    (A : TerminalGainModel Ω) :
    PosSMulInvariant (K0OfTerminalGainModel A) := by
  intro c hc f hf
  rcases hf with ⟨H, hHadm, hHgain⟩
  refine ⟨A.posSMulStrategy c hc H, A.admissible_posSMul hc hHadm, ?_⟩
  rw [A.terminalGain_posSMul hc, hHgain]

omit [MeasurableSpace Ω] in
theorem K0OfTerminalGainModel_claimCone
    (A : TerminalGainModel Ω) :
    ClaimCone (K0OfTerminalGainModel A) :=
  ⟨K0OfTerminalGainModel_hasZeroClaim A,
    K0OfTerminalGainModel_addInvariant A,
    K0OfTerminalGainModel_posSMulInvariant A⟩

end FTAPTheorem42
