/-
Copyright (c) 2026 selpo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: selpo
-/
import FTAPTheorem42.Stochastic.Integral.Local.Calculus.ActualStopping
import FTAPTheorem42.Stochastic.Integral.Local.Construction.GraphUniqueness
import FTAPTheorem42.Stochastic.Integral.Local.Construction.HorizonGraph

/-!
# Fixed-source integral graphs from the intrinsic local-completed carrier

This special-certificate stochastic-integral graph records an integrand and a
gain without exposing a selected special-decomposition representative in its
data.  This module supplies that graph relation for one fixed intrinsic
local-completed source. A witness contains an actual local representative,
while `IsIntegralGraph` hides the choice behind `Nonempty`.

The pair-refinement uniqueness theorem proves that the gain is well-defined up
to indistinguishability.  Thus selecting an actual representative is an
implementation bridge. The existence of a special decomposition remains a
restriction on the gain; this graph is not the general measure-independent
market graph. In particular, hiding the representative does not justify
unconditional transport between equivalent measures.
-/

namespace FTAPTheorem42

open Filter MeasureTheory
open scoped NNReal ProbabilityTheory

variable {Omega : Type*} [MeasurableSpace Omega]

namespace LocalCompletedM2A

variable {S : Process Omega}
  {F : Filtration NNReal (inferInstance : MeasurableSpace Omega)}
  {mu : Measure Omega} [IsProbabilityMeasure mu]
  {D : SpecialSemimartingaleDecomposition S F mu}

/-- Data witnessing that an integrand and a gain form an intrinsic
local-completed stochastic-integral graph. -/
structure IntegralGraphWitness
    (G : LocallySIntegrableStrategy D)
    (integrand gain : Process Omega) where
  actual : ActualLocallySIntegrableStrategy (realizationModel G)
  integrand_eq : actual.val.integrand = integrand
  gain_indistinguishable :
    ProcessIndistinguishable mu actual.val.stochasticIntegral gain

/-- The decomposition-hidden graph relation generated by the intrinsic
local-completed realization model. -/
def IsIntegralGraph
    (G : LocallySIntegrableStrategy D)
    (integrand gain : Process Omega) : Prop :=
  Nonempty (IntegralGraphWitness G integrand gain)

namespace IsIntegralGraph

/-- Select an actual local representative of a fixed-source integral graph. -/
noncomputable def representative
    {G : LocallySIntegrableStrategy D}
    {integrand gain : Process Omega}
    (h : IsIntegralGraph G integrand gain) :
    ActualLocallySIntegrableStrategy (realizationModel G) :=
  (Classical.choice h).actual

theorem representative_integrand
    {G : LocallySIntegrableStrategy D}
    {integrand gain : Process Omega}
    (h : IsIntegralGraph G integrand gain) :
    h.representative.val.integrand = integrand :=
  (Classical.choice h).integrand_eq

theorem representative_gain
    {G : LocallySIntegrableStrategy D}
    {integrand gain : Process Omega}
    (h : IsIntegralGraph G integrand gain) :
    ProcessIndistinguishable mu
      h.representative.val.stochasticIntegral gain :=
  (Classical.choice h).gain_indistinguishable

/-- For a fixed source, the intrinsic graph assigns at most one running gain
up to process indistinguishability to each predictable integrand. -/
theorem gain_indistinguishable
    [SigmaFiniteFiltration mu F]
    {G : LocallySIntegrableStrategy D}
    {integrand gainLeft gainRight : Process Omega}
    (hLeft : IsIntegralGraph G integrand gainLeft)
    (hRight : IsIntegralGraph G integrand gainRight) :
    ProcessIndistinguishable mu gainLeft gainRight := by
  let left := hLeft.representative
  let right := hRight.representative
  have hIntegrand : left.val.integrand = right.val.integrand := by
    calc
      left.val.integrand = integrand := hLeft.representative_integrand
      _ = right.val.integrand := hRight.representative_integrand.symm
  have hActual :=
    stochasticIntegral_indistinguishable_of_integrand_eq_of_actualLocal left right hIntegrand
  exact hLeft.representative_gain.symm.trans
    (hActual.trans hRight.representative_gain)

end IsIntegralGraph

end LocalCompletedM2A

end FTAPTheorem42

namespace FTAPTheorem42

/-!
## Integral graphs from one common completed schedule

A concrete market integral can be compared with the intrinsic completion one
localization coordinate at a time.  This section packages precisely those
finite-horizon obligations and proves that they generate an actual-local
integral graph.  No global bounded-variation representative is required.
-/

open MeasureTheory
open scoped NNReal ProbabilityTheory

variable {Omega : Type*} [MeasurableSpace Omega]

namespace LocalCompletedM2A

open SIntegrableFiniteVariationBridge

variable {S : Process Omega}
  {F : Filtration NNReal (inferInstance : MeasurableSpace Omega)}
  [F.IsRightContinuous]
  {mu : Measure Omega} [IsProbabilityMeasure mu]
  [SigmaFiniteFiltration mu F]
  {D : SpecialSemimartingaleDecomposition S F mu}
  {G : LocallySIntegrableStrategy D}

/-- Finite-horizon completed semantics of one market integrand/gain pair
along a common exhaustive source schedule. -/
structure CommonScheduleIntegralGraphData
    (G : LocallySIntegrableStrategy D)
    (integrand gain : Process Omega) where
  schedule : LocalCompletedM2ASchedule G
  coefficient : ∀ n, FiniteHorizonM2ACoefficient
    (schedule.variationBridge n) (schedule.quadraticKernel n)
  coefficient_eq : ∀ n,
    (coefficient n).coefficient = Function.uncurry integrand
  stoppedGain_eq : ∀ n, ProcessIndistinguishable mu
    (MeasureTheory.stoppedProcess gain (schedule.localizer n))
    (finiteHorizonCompletedM2AGain schedule.usualConditions
      (schedule.horizon n) (schedule.quadraticKernel n)
        (schedule.variationBridge n) (schedule.martingale n)
          (schedule.terminal_memLp n) (coefficient n))

end LocalCompletedM2A

end FTAPTheorem42
