/-
Copyright (c) 2026 selpo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: selpo
-/
import FTAPTheorem42.Stochastic.Integral.Elementary.ElementarySemimartingaleBoundedness
import FTAPTheorem42.Stochastic.Integral.Elementary.DiscretePredictableIntegral
import FTAPTheorem42.Stochastic.Martingale.Basic.MartingaleChronologicalGrid

/-!
# Elementary strategies from finite-grid adapted coefficients

An adapted real coefficient sequence on a chronological grid defines a
predictable elementary strategy by placing its `k`-th coefficient on the
half-open interval from grid time `k` to grid time `k+1`.  This is the common
market-facing constructor used by the finite-grid stopping arguments.
-/

open MeasureTheory Set
open scoped BigOperators NNReal ProbabilityTheory

namespace FTAPTheorem42

variable {Omega : Type*} [MeasurableSpace Omega]

namespace ChronologicalGrid

variable {N : Nat} (G : ChronologicalGrid NNReal N)

/-- One predictable elementary interval generated by an adapted grid
coefficient. -/
noncomputable def adaptedElementaryBlock
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (K : Nat → Omega → Real)
    (hK : StronglyAdapted (G.sampledFiltration F) K) (k : Nat) :
    PredictableElementaryInterval F where
  interval :=
    { coefficient := K k
      startTime := fun _ => G.sampledTime k
      stopTime := fun _ => G.sampledTime (k + 1)
      start_le_stop := fun _ => G.sampledTime_mono (Nat.le_succ k) }
  startStopping := isStoppingTime_const F (G.sampledTime k)
  stopStopping := isStoppingTime_const F (G.sampledTime (k + 1))
  coefficient_measurable := by
    rw [IsStoppingTime.measurableSpace_const]
    exact (hK k).measurable

/-- The predictable elementary strategy generated by all grid
coefficients. -/
noncomputable def adaptedElementaryStrategy
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (K : Nat → Omega → Real)
    (hK : StronglyAdapted (G.sampledFiltration F) K) :
    PredictableElementaryStrategy F :=
  (List.range N).map fun k => G.adaptedElementaryBlock F K hK k

/-- A generated block carries its coefficient precisely on its grid
interval. -/
theorem adaptedElementaryBlock_integrand
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (K : Nat → Omega → Real)
    (hK : StronglyAdapted (G.sampledFiltration F) K)
    (k : Nat) (t : NNReal) (omega : Omega) :
    (G.adaptedElementaryBlock F K hK k).integrand t omega =
      if t ∈ Ioc (G.sampledTime k) (G.sampledTime (k + 1)) then
        K k omega
      else 0 := by
  rfl

/-- A coefficient bound is inherited by the generated elementary
integrand because chronological grid intervals do not overlap. -/
theorem abs_adaptedElementaryStrategy_integrand_le
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (K : Nat → Omega → Real)
    (hK : StronglyAdapted (G.sampledFiltration F) K)
    {C : Real} (hC : 0 ≤ C) (hKBound : ∀ k omega, |K k omega| ≤ C)
    (t : NNReal) (omega : Omega) :
    |(G.adaptedElementaryStrategy F K hK).integrand t omega| ≤ C := by
  classical
  unfold adaptedElementaryStrategy PredictableElementaryStrategy.integrand
  simp only [List.map_map]
  rw [← List.sum_toFinset _ List.nodup_range]
  simp only [List.toFinset_range, Finset.sum_apply, Function.comp_apply]
  by_cases hActive : ∃ k ∈ Finset.range N,
      t ∈ Ioc (G.sampledTime k) (G.sampledTime (k + 1))
  · obtain ⟨k, hk, htk⟩ := hActive
    rw [Finset.sum_eq_single k]
    · rw [G.adaptedElementaryBlock_integrand F K hK k t omega]
      simpa [htk] using hKBound k omega
    · intro j hj hjne
      have hnot : t ∉ Ioc (G.sampledTime j) (G.sampledTime (j + 1)) := by
        intro htj
        rcases lt_or_gt_of_ne hjne with hjk | hkj
        · have hEndLe : G.sampledTime (j + 1) ≤ G.sampledTime k :=
            G.sampledTime_mono (Nat.succ_le_of_lt hjk)
          exact (not_le_of_gt (hEndLe.trans_lt htk.1)) htj.2
        · have hStartGe : G.sampledTime (k + 1) ≤ G.sampledTime j :=
            G.sampledTime_mono (Nat.succ_le_of_lt hkj)
          exact (not_lt_of_ge (htk.2.trans hStartGe)) htj.1
      rw [G.adaptedElementaryBlock_integrand F K hK j t omega]
      simp [hnot]
    · simp [hk]
  · have hnot (k : Nat) (hk : k ∈ Finset.range N) :
        t ∉ Ioc (G.sampledTime k) (G.sampledTime (k + 1)) :=
      fun htk => hActive ⟨k, hk, htk⟩
    rw [Finset.sum_eq_zero]
    · simpa using hC
    · intro k hk
      rw [G.adaptedElementaryBlock_integrand F K hK k t omega]
      simp [hnot k hk]

/-- At the terminal grid time, the generated strategy realizes the discrete
predictable integral of its coefficient against the sampled source. -/
theorem adaptedElementaryStrategy_gain_last
    (S : Process Omega)
    (F : Filtration NNReal (inferInstance : MeasurableSpace Omega))
    (K : Nat → Omega → Real)
    (hK : StronglyAdapted (G.sampledFiltration F) K) (omega : Omega) :
    ElementaryStrategy.gain S
        (G.adaptedElementaryStrategy F K hK).toElementary
        (G.sampledTime N) omega =
      discretePredictableIntegral K (G.natSample S) N omega := by
  classical
  unfold adaptedElementaryStrategy adaptedElementaryBlock
    PredictableElementaryStrategy.toElementary ElementaryStrategy.gain
    discretePredictableIntegral
  simp only [List.map_map]
  rw [← List.sum_toFinset _ List.nodup_range]
  simp only [List.toFinset_range]
  apply Finset.sum_congr rfl
  intro k hk
  rw [Finset.mem_range] at hk
  have hStop : G.sampledTime (k + 1) ≤ G.sampledTime N :=
    G.sampledTime_mono (Nat.succ_le_of_lt hk)
  have hStart : G.sampledTime k ≤ G.sampledTime N :=
    G.sampledTime_mono hk.le
  change K k omega *
      (S (min (G.sampledTime N) (G.sampledTime (k + 1))) omega -
        S (min (G.sampledTime N) (G.sampledTime k)) omega) = _
  rw [min_eq_right hStop, min_eq_right hStart]
  rfl

end ChronologicalGrid

end FTAPTheorem42
