/-
Copyright (c) 2026 selpo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: selpo
-/
import FTAPTheorem42.Stochastic.Predictable.PredictableKernelIntegral
import FTAPTheorem42.Stochastic.Integral.Calculus.SIntegrableDoleansCumulative
import FTAPTheorem42.Stochastic.Integral.Calculus.SIntegrableFiniteVariationIntegral
import FTAPTheorem42.Stochastic.Integral.Calculus.SIntegrableStrategyAlgebra

/-!
# Martingale residual of the pathwise Doléans density integral

The canonical predictable signed measure has two descriptions: it is the
integrated Stieltjes measure of the original finite-variation component, and
it is the corrected predictable density against integrated pathwise Jordan
variation.  Comparing these descriptions on predictable rectangles makes
the difference between the original component and the cumulative density
integral a martingale.
-/

open Filter MeasureTheory ProbabilityTheory Set
open scoped ENNReal NNReal ProbabilityTheory Topology

namespace FTAPTheorem42

variable {Ω : Type*} [MeasurableSpace Ω]

namespace SIntegrableFiniteVariationBridge

variable {S : Process Ω}
  {ℱ : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)}
  {μ : Measure Ω} [IsFiniteMeasure μ]
  {D : SpecialSemimartingaleDecomposition S ℱ μ}
  {H : SIntegrableStrategy D}

/-- The kernel whose path measure is the full Jordan total variation. -/
noncomputable def canonicalTotalVariationKernel
    (E : SIntegrableFiniteVariationBridge H) : Kernel Ω ℝ≥0 :=
  canonicalPositiveKernel E + canonicalNegativeKernel E

noncomputable instance canonicalTotalVariationKernel.instIsFiniteKernel
    (E : SIntegrableFiniteVariationBridge H) :
    IsFiniteKernel (canonicalTotalVariationKernel E) := by
  let : IsFiniteKernel (canonicalPositiveKernel E) :=
    isFiniteKernel_canonicalPositiveKernel E
  let : IsFiniteKernel (canonicalNegativeKernel E) :=
    isFiniteKernel_canonicalNegativeKernel E
  unfold canonicalTotalVariationKernel
  infer_instance

@[simp]
theorem canonicalTotalVariationKernel_apply
    (E : SIntegrableFiniteVariationBridge H) (ω : Ω) :
    canonicalTotalVariationKernel E ω =
      E.referenceDensity ω •
        (FiniteVariationPath.signedMeasure
          (H.finiteVariationPart_isBoundedVariation ω)).totalVariation := by
  rw [canonicalTotalVariationKernel, add_apply,
    canonicalPositiveKernel_apply, canonicalNegativeKernel_apply]
  rw [← smul_add]
  rfl

/-- Integrated total variation is the predictable measure generated by the
total-variation kernel. -/
theorem predictableMeasure_canonicalTotalVariationKernel_eq
    (E : SIntegrableFiniteVariationBridge H) :
    PredictableKernelMeasure.predictableMeasure ℱ μ
        (canonicalTotalVariationKernel E) =
      canonicalVariationMeasure E := by
  let : IsFiniteKernel (canonicalPositiveKernel E) :=
    isFiniteKernel_canonicalPositiveKernel E
  let : IsFiniteKernel (canonicalNegativeKernel E) :=
    isFiniteKernel_canonicalNegativeKernel E
  rw [canonicalTotalVariationKernel,
    PredictableKernelMeasure.predictableMeasure_add]
  rfl

/-- Fubini identity for integrated pathwise Jordan variation. -/
theorem canonicalVariationIntegral_eq_pathIntegral
    (E : SIntegrableFiniteVariationBridge H)
    {K : ℝ≥0 → Ω → ℝ}
    (hK : StronglyMeasurable[ℱ.predictable] (Function.uncurry K))
    (hKInt : Integrable (Function.uncurry K)
      (PredictableKernelMeasure.swappedCompProd μ
        (canonicalTotalVariationKernel E))) :
    (∫ p, Function.uncurry K p ∂canonicalVariationMeasure E) =
      ∫ ω, ∫ t, K t ω
        ∂(FiniteVariationPath.signedMeasure
          (H.finiteVariationPart_isBoundedVariation ω)).totalVariation
        ∂E.referenceMeasure := by
  rw [← predictableMeasure_canonicalTotalVariationKernel_eq E]
  have hFubini :=
    PredictableKernelMeasure.integral_predictableMeasure_eq_integral_kernel
      (ℱ := ℱ) hK hKInt
  calc
    (∫ p, Function.uncurry K p
        ∂PredictableKernelMeasure.predictableMeasure ℱ μ
          (canonicalTotalVariationKernel E)) =
        ∫ ω, ∫ t, K t ω ∂canonicalTotalVariationKernel E ω ∂μ :=
      hFubini
    _ = ∫ ω, E.referenceDensity ω •
        (∫ t, K t ω
          ∂(FiniteVariationPath.signedMeasure
            (H.finiteVariationPart_isBoundedVariation ω)).totalVariation) ∂μ := by
      apply integral_congr_ae
      filter_upwards with ω
      rw [canonicalTotalVariationKernel_apply,
        integral_smul_nnreal_measure]
    _ = ∫ ω, ∫ t, K t ω
        ∂(FiniteVariationPath.signedMeasure
          (H.finiteVariationPart_isBoundedVariation ω)).totalVariation
        ∂E.referenceMeasure := by
      exact (integral_withDensity_eq_integral_smul
        E.referenceDensity_measurable _).symm

private theorem integrable_swappedCompProd_of_abs_le_one
    {κ : Kernel Ω ℝ≥0} [IsFiniteKernel κ]
    {K : ℝ≥0 → Ω → ℝ}
    (hK : StronglyMeasurable[ℱ.predictable] (Function.uncurry K))
    (hBound : ∀ t ω, |K t ω| ≤ 1) :
    Integrable (Function.uncurry K)
      (PredictableKernelMeasure.swappedCompProd μ κ) := by
  have hKprod : StronglyMeasurable (Function.uncurry K) :=
    hK.mono (PredictableKernelMeasure.predictable_le_prod ℱ)
  let : IsFiniteMeasure
      (PredictableKernelMeasure.swappedCompProd μ κ) := by
    unfold PredictableKernelMeasure.swappedCompProd
    infer_instance
  apply (integrable_const (1 : ℝ)).mono' hKprod.aestronglyMeasurable
  filter_upwards with p
  rw [Real.norm_eq_abs]
  exact hBound p.1 p.2

/-- The canonical predictable signed measure of a rectangle is the expected
original finite-variation increment over its sample event. -/
theorem canonicalMeasure_Ioc_prod_eq_setIntegral_finiteVariationIncrement
    (E : SIntegrableFiniteVariationBridge H)
    {a b : ℝ≥0} (hab : a ≤ b) {B : Set Ω}
    (hB : MeasurableSet[ℱ a] B) :
    E.canonicalMeasure (Ioc a b ×ˢ B) =
      ∫ ω in B,
        (H.finiteVariationPart b ω - H.finiteVariationPart a ω)
        ∂E.referenceMeasure := by
  let R : Set (ℝ≥0 × Ω) := Ioc a b ×ˢ B
  let K : ℝ≥0 → Ω → ℝ :=
    PredictableProcess.restrict R (fun _ _ => 1)
  have hR : MeasurableSet[ℱ.predictable] R :=
    measurableSet_predictable_Ioc_prod a b hB
  have hK : StronglyMeasurable[ℱ.predictable] (Function.uncurry K) :=
    PredictableProcess.isStronglyPredictable_restrict hR stronglyMeasurable_const
  have hBound : ∀ t ω, |K t ω| ≤ 1 := by
    intro t ω
    by_cases hp : (t, ω) ∈ R <;>
      simp [K, hp]
  let : IsFiniteKernel (canonicalPositiveKernel E) :=
    isFiniteKernel_canonicalPositiveKernel E
  let : IsFiniteKernel (canonicalNegativeKernel E) :=
    isFiniteKernel_canonicalNegativeKernel E
  have hKp : Integrable (Function.uncurry K)
      (PredictableKernelMeasure.swappedCompProd μ
        (canonicalPositiveKernel E)) :=
    integrable_swappedCompProd_of_abs_le_one hK hBound
  have hKn : Integrable (Function.uncurry K)
      (PredictableKernelMeasure.swappedCompProd μ
        (canonicalNegativeKernel E)) :=
    integrable_swappedCompProd_of_abs_le_one hK hBound
  have hLeft : PredictableSignedMeasure.integral E.canonicalMeasure K =
      E.canonicalMeasure R := by
    let : MeasurableSpace (ℝ≥0 × Ω) := ℱ.predictable
    let : IsFiniteMeasure (VectorMeasure.variation E.canonicalMeasure) := by
      rw [← signedMeasure_totalVariation_eq_variation]
      exact isFiniteMeasure_of_le (canonicalVariationMeasure E)
        (totalVariation_canonicalMeasure_le_canonicalVariationMeasure E)
    change (∫ᵛ p, R.indicator (fun _ : ℝ≥0 × Ω => (1 : ℝ)) p
      ∂•E.canonicalMeasure) = E.canonicalMeasure R
    simpa [ContinuousLinearMap.lsmul_apply] using
      (VectorMeasure.integral_indicator_const
        (μ := E.canonicalMeasure)
        (B := ContinuousLinearMap.lsmul ℝ ℝ) (1 : ℝ) hR)
  have hPath (ω : Ω) :
      FiniteVariationPath.integral
          (H.finiteVariationPart_isBoundedVariation ω) (fun t => K t ω) =
        B.indicator (fun ω =>
          H.finiteVariationPart b ω - H.finiteVariationPart a ω) ω := by
    by_cases hω : ω ∈ B
    · have hSection : (fun t => K t ω) =
          (Ioc a b).indicator (fun _ => (1 : ℝ)) := by
        funext t
        by_cases ht : t ∈ Ioc a b <;>
          simp [K, R, hω, ht]
      rw [hSection, FiniteVariationPath.integral_indicator
        (H.finiteVariationPart_isBoundedVariation ω) measurableSet_Ioc,
        FiniteVariationPath.setIntegral_const_Ioc
          (H.finiteVariationPart_isBoundedVariation ω)
          (E.rightContinuous ω) hab]
      simp [hω]
    · have hSection : (fun t => K t ω) = 0 := by
        funext t
        simp [K, R, hω]
      rw [hSection]
      simp [FiniteVariationPath.integral, hω]
  have hCanonical := canonicalIntegral_eq_pathIntegral E hK hKp hKn
  rw [hLeft] at hCanonical
  calc
    E.canonicalMeasure (Ioc a b ×ˢ B) =
        ∫ ω, FiniteVariationPath.integral
          (H.finiteVariationPart_isBoundedVariation ω) (fun t => K t ω)
          ∂E.referenceMeasure :=
      hCanonical
    _ = ∫ ω in B,
        (H.finiteVariationPart b ω - H.finiteVariationPart a ω)
        ∂E.referenceMeasure := by
      rw [← integral_indicator (ℱ.le a B hB)]
      exact integral_congr_ae (Eventually.of_forall hPath)

/-- The same rectangle mass is the expected increment of the cumulative
density integral. -/
theorem canonicalMeasure_Ioc_prod_eq_setIntegral_cumulativeDensityIncrement
    (E : SIntegrableFiniteVariationBridge H)
    {a b : ℝ≥0} (hab : a ≤ b) {B : Set Ω}
    (hB : MeasurableSet[ℱ a] B) :
    E.canonicalMeasure (Ioc a b ×ˢ B) =
      ∫ ω in B,
        (cumulativeDensityIntegral E b ω -
          cumulativeDensityIntegral E a ω) ∂E.referenceMeasure := by
  let R : Set (ℝ≥0 × Ω) := Ioc a b ×ˢ B
  let K : ℝ≥0 → Ω → ℝ := PredictableProcess.restrict R
    (fun t ω => jumpCorrectedCanonicalVariationDensity E (t, ω))
  have hR : MeasurableSet[ℱ.predictable] R :=
    measurableSet_predictable_Ioc_prod a b hB
  have hK : StronglyMeasurable[ℱ.predictable] (Function.uncurry K) :=
    PredictableProcess.isStronglyPredictable_restrict hR
      (jumpCorrectedCanonicalVariationDensity_stronglyMeasurable E)
  have hBound : ∀ t ω, |K t ω| ≤ 1 := by
    intro t ω
    by_cases hp : (t, ω) ∈ R
    · simp only [K, PredictableProcess.restrict_apply_of_mem hp]
      exact abs_jumpCorrectedCanonicalVariationDensity_le_one E (t, ω)
    · simp [K, hp]
  have hKInt : Integrable (Function.uncurry K)
      (PredictableKernelMeasure.swappedCompProd μ
        (canonicalTotalVariationKernel E)) :=
    integrable_swappedCompProd_of_abs_le_one hK hBound
  have hDensityInt : Integrable
      (jumpCorrectedCanonicalVariationDensity E)
      (canonicalVariationMeasure E) := by
    apply (integrable_const (1 : ℝ)).mono'
      (jumpCorrectedCanonicalVariationDensity_stronglyMeasurable E
        |>.aestronglyMeasurable)
    filter_upwards with p
    rw [Real.norm_eq_abs]
    exact abs_jumpCorrectedCanonicalVariationDensity_le_one E p
  have hRepresentation := congrArg
    (fun m : @SignedMeasure (ℝ≥0 × Ω) ℱ.predictable => m R)
    (withDensity_jumpCorrectedCanonicalVariationDensity_eq_canonicalMeasure E)
  rw [withDensityᵥ_apply hDensityInt hR] at hRepresentation
  have hLeft : E.canonicalMeasure R =
      ∫ p, Function.uncurry K p ∂canonicalVariationMeasure E := by
    calc
      E.canonicalMeasure R =
          ∫ p in R, jumpCorrectedCanonicalVariationDensity E p
            ∂canonicalVariationMeasure E := hRepresentation.symm
      _ = ∫ p, Function.uncurry K p ∂canonicalVariationMeasure E := by
        rw [← integral_indicator hR]
        rfl
  have hPath (ω : Ω) :
      (∫ t, K t ω
        ∂(FiniteVariationPath.signedMeasure
          (H.finiteVariationPart_isBoundedVariation ω)).totalVariation) =
        B.indicator (fun ω =>
          cumulativeDensityIntegral E b ω -
            cumulativeDensityIntegral E a ω) ω := by
    by_cases hω : ω ∈ B
    · have hSection : (fun t => K t ω) =
          (Ioc a b).indicator (fun t =>
            jumpCorrectedCanonicalVariationDensity E (t, ω)) := by
        funext t
        by_cases ht : t ∈ Ioc a b <;>
          simp [K, R, hω, ht]
      rw [hSection, integral_indicator measurableSet_Ioc,
        ← cumulativeDensityIntegral_sub E ω hab]
      simp [hω]
    · have hSection : (fun t => K t ω) = 0 := by
        funext t
        simp [K, R, hω]
      rw [hSection]
      simp [hω]
  have hFubini := canonicalVariationIntegral_eq_pathIntegral E hK hKInt
  rw [← hLeft] at hFubini
  calc
    E.canonicalMeasure (Ioc a b ×ˢ B) =
        ∫ ω, ∫ t, K t ω
          ∂(FiniteVariationPath.signedMeasure
            (H.finiteVariationPart_isBoundedVariation ω)).totalVariation
          ∂E.referenceMeasure :=
      hFubini
    _ = ∫ ω in B,
        (cumulativeDensityIntegral E b ω -
          cumulativeDensityIntegral E a ω) ∂E.referenceMeasure := by
      rw [← integral_indicator (ℱ.le a B hB)]
      exact integral_congr_ae (Eventually.of_forall hPath)

/-- The difference between the original finite-variation component and its
cumulative density integral, normalized to start at zero. -/
noncomputable def doleansResidual
    (E : SIntegrableFiniteVariationBridge H) : Process Ω :=
  fun t ω => H.finiteVariationPart t ω - H.finiteVariationPart 0 ω -
    cumulativeDensityIntegral E t ω

/-- The residual is strongly adapted. -/
theorem doleansResidual_stronglyAdapted
    (E : SIntegrableFiniteVariationBridge H) :
    StronglyAdapted ℱ (doleansResidual E) := by
  have hA := H.finiteVariationPart_isPredictable.stronglyAdapted
  have hA0 : StronglyAdapted ℱ
      (fun _ : ℝ≥0 => H.finiteVariationPart 0) := by
    intro t
    exact hA.stronglyMeasurable_le bot_le
  intro t
  change StronglyMeasurable[ℱ t] (fun ω =>
    H.finiteVariationPart t ω - H.finiteVariationPart 0 ω -
      cumulativeDensityIntegral E t ω)
  exact ((hA t).sub (hA0 t)).sub
    (cumulativeDensityIntegral_stronglyAdapted E t)

omit [IsFiniteMeasure μ] in
private theorem pathVariationReal_Ioc_le_univ
    (ω : Ω) (a b : ℝ≥0) :
    (FiniteVariationPath.signedMeasure
      (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
        (Ioc a b) ≤
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ := by
  let ν := FiniteVariationPath.signedMeasure
    (H.finiteVariationPart_isBoundedVariation ω)
  let : IsFiniteMeasure ν.totalVariation := by
    dsimp only [ν]
    unfold SignedMeasure.totalVariation
    infer_instance
  exact measureReal_mono (subset_univ _)

private theorem integrable_pathVariationReal_univ
    (E : SIntegrableFiniteVariationBridge H) :
    Integrable (fun ω =>
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ) E.referenceMeasure := by
  have : IsFiniteMeasure
      (μ.withDensity fun ω => (E.referenceDensity ω : ℝ≥0∞)) :=
    referenceMeasure.instIsFiniteMeasure E
  exact E.variationMemLpTwo.integrable (by norm_num)

/-- Every original finite-variation increment from time zero is bounded by
the path's total Jordan variation. -/
theorem abs_finiteVariationPart_sub_initial_le_pathVariation
    (E : SIntegrableFiniteVariationBridge H) (t : ℝ≥0) (ω : Ω) :
    |H.finiteVariationPart t ω - H.finiteVariationPart 0 ω| ≤
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ := by
  let ν := FiniteVariationPath.signedMeasure
    (H.finiteVariationPart_isBoundedVariation ω)
  have hUpper : ν (Ioc 0 t) ≤ ν.totalVariation.real (Ioc 0 t) :=
    signedMeasure_apply_le_totalVariation_real ν measurableSet_Ioc
  have hLower : -ν (Ioc 0 t) ≤ ν.totalVariation.real (Ioc 0 t) := by
    have h := signedMeasure_apply_le_totalVariation_real (-ν)
      (B := Ioc 0 t) measurableSet_Ioc
    simpa only [neg_apply, SignedMeasure.totalVariation_neg] using h
  have hLower' : -ν.totalVariation.real (Ioc 0 t) ≤ ν (Ioc 0 t) := by
    linarith
  have hMass : ν (Ioc 0 t) =
      H.finiteVariationPart t ω - H.finiteVariationPart 0 ω :=
    FiniteVariationPath.signedMeasure_Ioc
      (H.finiteVariationPart_isBoundedVariation ω)
      (E.rightContinuous ω) bot_le
  calc
    |H.finiteVariationPart t ω - H.finiteVariationPart 0 ω| =
        |ν (Ioc 0 t)| := by rw [hMass]
    _ ≤ ν.totalVariation.real (Ioc 0 t) := abs_le.2 ⟨hLower', hUpper⟩
    _ ≤ ν.totalVariation.real Set.univ :=
      pathVariationReal_Ioc_le_univ ω 0 t

/-- The cumulative density integral from time zero obeys the same
pathwise variation bound. -/
theorem abs_cumulativeDensityIntegral_le_pathVariation
    (E : SIntegrableFiniteVariationBridge H) (t : ℝ≥0) (ω : Ω) :
    |cumulativeDensityIntegral E t ω| ≤
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ := by
  have h := abs_cumulativeDensityIntegral_sub_le E ω (a := 0) (b := t) bot_le
  have hC0 : cumulativeDensityIntegral E 0 ω = 0 := by
    simp [cumulativeDensityIntegral, pathVariationMeasureUpTo]
  rw [hC0, sub_zero] at h
  have hVariation :
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          (Ioc 0 t) =
        cumulativeVariation H t ω - cumulativeVariation H 0 ω :=
    totalVariation_real_Ioc_eq_cumulativeVariation_sub H ω bot_le
  exact h.trans <| hVariation ▸ pathVariationReal_Ioc_le_univ ω 0 t

/-- The residual is bounded by twice the path's total Jordan variation. -/
theorem abs_doleansResidual_le_pathVariation
    (E : SIntegrableFiniteVariationBridge H) (t : ℝ≥0) (ω : Ω) :
    |doleansResidual E t ω| ≤
      2 * (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ := by
  rw [doleansResidual]
  calc
    |(H.finiteVariationPart t ω - H.finiteVariationPart 0 ω) -
        cumulativeDensityIntegral E t ω| ≤
        |H.finiteVariationPart t ω - H.finiteVariationPart 0 ω| +
          |cumulativeDensityIntegral E t ω| := abs_sub _ _
    _ ≤ _ + _ :=
      add_le_add (abs_finiteVariationPart_sub_initial_le_pathVariation E t ω)
        (abs_cumulativeDensityIntegral_le_pathVariation E t ω)
    _ = 2 * _ := by ring

/-- Every fixed-time residual is integrable under the equivalent reference
measure. -/
theorem integrable_doleansResidual
    (E : SIntegrableFiniteVariationBridge H) (t : ℝ≥0) :
    Integrable (doleansResidual E t) E.referenceMeasure := by
  have hVariation : Integrable (fun ω =>
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ) E.referenceMeasure :=
    integrable_pathVariationReal_univ E
  apply (hVariation.const_mul 2).mono'
    ((doleansResidual_stronglyAdapted E).stronglyMeasurable
      |>.aestronglyMeasurable)
  filter_upwards with ω
  rw [Real.norm_eq_abs]
  exact abs_doleansResidual_le_pathVariation E t ω

private theorem integrable_finiteVariationPart_sub
    (E : SIntegrableFiniteVariationBridge H) (a b : ℝ≥0) :
    Integrable (fun ω =>
      H.finiteVariationPart b ω - H.finiteVariationPart a ω)
      E.referenceMeasure := by
  have hA := H.finiteVariationPart_isPredictable.stronglyAdapted
  have hMeas : StronglyMeasurable (fun ω =>
      H.finiteVariationPart b ω - H.finiteVariationPart a ω) :=
    ((hA b).mono (ℱ.le b)).sub ((hA a).mono (ℱ.le a))
  have hVariation : Integrable (fun ω =>
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ) E.referenceMeasure :=
    integrable_pathVariationReal_univ E
  apply (hVariation.const_mul 2).mono'
    hMeas.aestronglyMeasurable
  filter_upwards with ω
  rw [Real.norm_eq_abs]
  calc
    |H.finiteVariationPart b ω - H.finiteVariationPart a ω| =
        |(H.finiteVariationPart b ω - H.finiteVariationPart 0 ω) -
          (H.finiteVariationPart a ω - H.finiteVariationPart 0 ω)| := by
      congr 1
      ring
    _ ≤ |H.finiteVariationPart b ω - H.finiteVariationPart 0 ω| +
        |H.finiteVariationPart a ω - H.finiteVariationPart 0 ω| := abs_sub _ _
    _ ≤ _ + _ :=
      add_le_add (abs_finiteVariationPart_sub_initial_le_pathVariation E b ω)
        (abs_finiteVariationPart_sub_initial_le_pathVariation E a ω)
    _ = 2 * _ := by ring

private theorem integrable_cumulativeDensityIntegral_sub
    (E : SIntegrableFiniteVariationBridge H) (a b : ℝ≥0) :
    Integrable (fun ω => cumulativeDensityIntegral E b ω -
      cumulativeDensityIntegral E a ω) E.referenceMeasure := by
  have hC := cumulativeDensityIntegral_stronglyAdapted E
  have hMeas : StronglyMeasurable (fun ω =>
      cumulativeDensityIntegral E b ω -
        cumulativeDensityIntegral E a ω) :=
    ((hC b).mono (ℱ.le b)).sub ((hC a).mono (ℱ.le a))
  have hVariation : Integrable (fun ω =>
      (FiniteVariationPath.signedMeasure
        (H.finiteVariationPart_isBoundedVariation ω)).totalVariation.real
          Set.univ) E.referenceMeasure :=
    integrable_pathVariationReal_univ E
  apply (hVariation.const_mul 2).mono'
    hMeas.aestronglyMeasurable
  filter_upwards with ω
  rw [Real.norm_eq_abs]
  exact (abs_sub _ _).trans <|
    (add_le_add (abs_cumulativeDensityIntegral_le_pathVariation E b ω)
      (abs_cumulativeDensityIntegral_le_pathVariation E a ω)).trans_eq (by ring)

/-- Residual set integrals are constant between deterministic times. -/
theorem setIntegral_doleansResidual_eq
    (E : SIntegrableFiniteVariationBridge H)
    {a b : ℝ≥0} (hab : a ≤ b) {B : Set Ω}
    (hB : MeasurableSet[ℱ a] B) :
    ∫ ω in B, doleansResidual E a ω ∂E.referenceMeasure =
      ∫ ω in B, doleansResidual E b ω ∂E.referenceMeasure := by
  have hIncrement :
      (∫ ω in B,
        (H.finiteVariationPart b ω - H.finiteVariationPart a ω)
          ∂E.referenceMeasure) =
      ∫ ω in B,
        (cumulativeDensityIntegral E b ω -
          cumulativeDensityIntegral E a ω) ∂E.referenceMeasure :=
    (canonicalMeasure_Ioc_prod_eq_setIntegral_finiteVariationIncrement
      E hab hB).symm.trans
        (canonicalMeasure_Ioc_prod_eq_setIntegral_cumulativeDensityIncrement
          E hab hB)
  rw [← sub_eq_zero]
  rw [← integral_sub (integrable_doleansResidual E a).integrableOn
    (integrable_doleansResidual E b).integrableOn]
  have hPoint : (fun ω =>
      doleansResidual E a ω - doleansResidual E b ω) =
      fun ω =>
        (cumulativeDensityIntegral E b ω -
          cumulativeDensityIntegral E a ω) -
        (H.finiteVariationPart b ω - H.finiteVariationPart a ω) := by
    funext ω
    simp only [doleansResidual]
    ring
  rw [hPoint, integral_sub
    (integrable_cumulativeDensityIntegral_sub E a b).integrableOn
    (integrable_finiteVariationPart_sub E a b).integrableOn,
    hIncrement, sub_self]

/-- The Doléans comparison residual is a true martingale. -/
theorem doleansResidual_martingale
    (E : SIntegrableFiniteVariationBridge H) :
    Martingale (doleansResidual E) ℱ E.referenceMeasure := by
  have hSub : Submartingale (doleansResidual E) ℱ E.referenceMeasure :=
    submartingale_of_setIntegral_le (doleansResidual_stronglyAdapted E)
      (integrable_doleansResidual E) fun a b hab B hB =>
        (setIntegral_doleansResidual_eq E hab hB).le
  have hNegSub : Submartingale (-doleansResidual E) ℱ E.referenceMeasure :=
    submartingale_of_setIntegral_le (doleansResidual_stronglyAdapted E).neg
      (fun t => (integrable_doleansResidual E t).neg) fun a b hab B hB => by
        change (∫ ω in B, -doleansResidual E a ω ∂E.referenceMeasure) ≤
          ∫ ω in B, -doleansResidual E b ω ∂E.referenceMeasure
        rw [integral_neg, integral_neg,
          setIntegral_doleansResidual_eq E hab hB]
  have hSuper : Supermartingale (doleansResidual E) ℱ E.referenceMeasure := by
    simpa using hNegSub.neg
  exact (martingale_iff).2 ⟨hSuper, hSub⟩

/-- The cumulative density integral has left limits on every path. -/
theorem cumulativeDensityIntegral_hasLeftLimits
    (E : SIntegrableFiniteVariationBridge H) :
    ProcessHasLeftLimits (cumulativeDensityIntegral E) := by
  intro ω t
  exact (cumulativeDensityIntegral_isBoundedVariation E ω).tendsto_leftLim t

private theorem finiteVariationInitial_hasLeftLimits
    (_E : SIntegrableFiniteVariationBridge H) :
    ProcessHasLeftLimits (fun _ : ℝ≥0 => H.finiteVariationPart 0) := by
  intro ω t
  exact tendsto_leftLim_of_tendsto ⟨H.finiteVariationPart 0 ω,
    tendsto_const_nhds⟩

/-- Residual paths have left limits. -/
theorem doleansResidual_hasLeftLimits
    (E : SIntegrableFiniteVariationBridge H) :
    ProcessHasLeftLimits (doleansResidual E) := by
  change ProcessHasLeftLimits (fun t ω =>
    (H.finiteVariationPart t ω - H.finiteVariationPart 0 ω) -
      cumulativeDensityIntegral E t ω)
  exact (H.finiteVariationPart_hasLeftLimits.sub
    (finiteVariationInitial_hasLeftLimits E)).sub
      (cumulativeDensityIntegral_hasLeftLimits E)

/-- Residual paths are right-continuous. -/
theorem doleansResidual_rightContinuous
    (E : SIntegrableFiniteVariationBridge H) (ω : Ω) (t : ℝ≥0) :
    ContinuousWithinAt (fun u => doleansResidual E u ω) (Set.Ici t) t := by
  change ContinuousWithinAt (fun u =>
    (H.finiteVariationPart u ω - H.finiteVariationPart 0 ω) -
      cumulativeDensityIntegral E u ω) (Set.Ici t) t
  exact ((E.rightContinuous ω t).sub continuousWithinAt_const).sub
    (cumulativeDensityIntegral_rightContinuous E ω t)

/-- All left jumps of the residual vanish. -/
theorem processLeftJump_doleansResidual_eq_zero
    (E : SIntegrableFiniteVariationBridge H) (t : ℝ≥0) (ω : Ω) :
    processLeftJump (doleansResidual E) t ω = 0 := by
  let A0 : Process Ω := fun _ => H.finiteVariationPart 0
  have hA0 := finiteVariationInitial_hasLeftLimits E
  have hA0Jump : processLeftJump A0 t ω = 0 := by
    unfold processLeftJump
    rcases eq_or_neBot (𝓝[<] t) with hbot | hne
    · rw [leftLim_eq_of_eq_bot _ hbot]
      exact sub_self _
    · rw [show Function.leftLim (fun _ : ℝ≥0 => A0 t ω) t = A0 t ω by
        apply leftLim_eq_of_tendsto
        exact tendsto_const_nhds]
      exact sub_self _
  change processLeftJump (fun s ω =>
    (H.finiteVariationPart s ω - A0 s ω) -
      cumulativeDensityIntegral E s ω) t ω = 0
  rw [processLeftJump_sub
      (H.finiteVariationPart_hasLeftLimits.sub hA0)
      (cumulativeDensityIntegral_hasLeftLimits E),
    processLeftJump_sub H.finiteVariationPart_hasLeftLimits hA0,
    hA0Jump, sub_zero, processLeftJump_cumulativeDensityIntegral_eq E t ω,
    sub_self]

/-- Vanishing jumps and right continuity upgrade every residual path to a
continuous function. -/
theorem doleansResidual_continuous
    (E : SIntegrableFiniteVariationBridge H) (ω : Ω) :
    Continuous fun t => doleansResidual E t ω := by
  apply continuous_iff_continuousAt.2
  intro t
  apply continuousAt_iff_continuous_left'_right'.2
  constructor
  · have hJump := processLeftJump_doleansResidual_eq_zero E t ω
    have hLeftEq : Function.leftLim (fun s => doleansResidual E s ω) t =
        doleansResidual E t ω := by
      unfold processLeftJump at hJump
      linarith
    change Tendsto (fun s => doleansResidual E s ω) (𝓝[<] t)
      (𝓝 (doleansResidual E t ω))
    rw [← hLeftEq]
    exact doleansResidual_hasLeftLimits E ω t
  · exact (doleansResidual_rightContinuous E ω t).mono Ioi_subset_Ici_self

end SIntegrableFiniteVariationBridge

end FTAPTheorem42
