/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/
import FTAPTheorem42.Stochastic.Predictable.PredictableKernelIntegral
import FTAPTheorem42.Stochastic.Integral.Calculus.SIntegrableFiniteVariationBridge

/-!
# Pathwise finite-variation integral bridge

The predictable signed measure generated by a finite-variation component is
the sample-space aggregate of its pathwise Jordan measures.  This file
connects the iterated-kernel identity to the pathwise Stieltjes integral for
integrands satisfying the explicit kernel-integrability hypotheses.  It does
not construct the general stochastic integral or its closedness.
-/

open Filter MeasureTheory ProbabilityTheory Set
open scoped ENNReal NNReal Topology ProbabilityTheory

namespace FTAPTheorem42

variable {Ω : Type*} [MeasurableSpace Ω]

namespace FiniteVariationKernel

variable {Time : Type*} [MeasurableSpace Time]
  [LinearOrder Time] [DenselyOrdered Time]
  [TopologicalSpace Time] [OrderTopology Time]
  [SecondCountableTopology Time] [CompactIccSpace Time]
  [BorelSpace Time]

omit [MeasurableSpace Ω] in
theorem pathIntegral_eq_positive_sub_negative
    {A : Time → Ω → ℝ}
    (hA : ∀ ω, BoundedVariationOn (fun t => A t ω) Set.univ)
    (ω : Ω) (K : Time → ℝ)
    (hKp : Integrable K (positivePathMeasure hA ω))
    (hKn : Integrable K (negativePathMeasure hA ω)) :
    FiniteVariationPath.integral (hA ω) K =
      (∫ t, K t ∂positivePathMeasure hA ω) -
        ∫ t, K t ∂negativePathMeasure hA ω := by
  have hp : VectorMeasure.Integrable
      ((positivePathMeasure hA ω).toSignedMeasure : VectorMeasure Time ℝ) K := by
    change Integrable K
      (VectorMeasure.variation
        ((positivePathMeasure hA ω).toSignedMeasure : VectorMeasure Time ℝ))
    rw [Measure.variation_toSignedMeasure]
    exact hKp
  have hn : VectorMeasure.Integrable
      ((negativePathMeasure hA ω).toSignedMeasure : VectorMeasure Time ℝ) K := by
    change Integrable K
      (VectorMeasure.variation
        ((negativePathMeasure hA ω).toSignedMeasure : VectorMeasure Time ℝ))
    rw [Measure.variation_toSignedMeasure]
    exact hKn
  have hmeasure :
      (positivePathMeasure hA ω).toSignedMeasure -
          (negativePathMeasure hA ω).toSignedMeasure =
        FiniteVariationPath.signedMeasure (hA ω) :=
    SignedMeasure.toSignedMeasure_toJordanDecomposition
      (FiniteVariationPath.signedMeasure (hA ω))
  calc
    FiniteVariationPath.integral (hA ω) K =
        ∫ᵛ t, K t ∂•
          ((positivePathMeasure hA ω).toSignedMeasure -
            (negativePathMeasure hA ω).toSignedMeasure) := by
      unfold FiniteVariationPath.integral
      rw [hmeasure]
    _ = (∫ᵛ t, K t ∂•(positivePathMeasure hA ω).toSignedMeasure) -
          ∫ᵛ t, K t ∂•(negativePathMeasure hA ω).toSignedMeasure := by
      exact VectorMeasure.integral_sub_vectorMeasure hp hn
    _ = (∫ t, K t ∂positivePathMeasure hA ω) -
          ∫ t, K t ∂negativePathMeasure hA ω := by
      rw [PredictableSignedMeasure.vectorIntegral_toSignedMeasure,
        PredictableSignedMeasure.vectorIntegral_toSignedMeasure]

end FiniteVariationKernel

namespace SIntegrableFiniteVariationBridge

variable {S : Process Ω}
  {ℱ : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)}
  {μ : Measure Ω} [IsFiniteMeasure μ]
  {D : SpecialSemimartingaleDecomposition S ℱ μ}
  {H : SIntegrableStrategy D}

theorem canonicalIntegral_eq_pathIntegral
    (E : SIntegrableFiniteVariationBridge H)
    {K : ℝ≥0 → Ω → ℝ}
    (hK : StronglyMeasurable[ℱ.predictable] (Function.uncurry K))
    (hKp : Integrable (Function.uncurry K)
      (PredictableKernelMeasure.swappedCompProd μ
        (canonicalPositiveKernel E)))
    (hKn : Integrable (Function.uncurry K)
      (PredictableKernelMeasure.swappedCompProd μ
        (canonicalNegativeKernel E))) :
    PredictableSignedMeasure.integral E.canonicalMeasure K =
      ∫ ω, FiniteVariationPath.integral
        (H.finiteVariationPart_isBoundedVariation ω)
        (fun t => K t ω) ∂E.referenceMeasure := by
  let : IsFiniteKernel (canonicalPositiveKernel E) :=
    isFiniteKernel_canonicalPositiveKernel E
  let : IsFiniteKernel (canonicalNegativeKernel E) :=
    isFiniteKernel_canonicalNegativeKernel E
  have hKprod : StronglyMeasurable (Function.uncurry K) :=
    hK.mono (PredictableKernelMeasure.predictable_le_prod ℱ)
  have hKpComp : Integrable
      (fun p : Ω × ℝ≥0 => Function.uncurry K (Prod.swap p))
      (μ ⊗ₘ canonicalPositiveKernel E) := by
    exact (integrable_map_measure hKprod.aestronglyMeasurable
      measurable_swap.aemeasurable).1 hKp
  have hKnComp : Integrable
      (fun p : Ω × ℝ≥0 => Function.uncurry K (Prod.swap p))
      (μ ⊗ₘ canonicalNegativeKernel E) := by
    exact (integrable_map_measure hKprod.aestronglyMeasurable
      measurable_swap.aemeasurable).1 hKn
  have hKpPath : ∀ᵐ ω ∂μ, Integrable (fun t => K t ω)
      (FiniteVariationKernel.positivePathMeasure
        H.finiteVariationPart_isBoundedVariation ω) := by
    have h := hKpComp.ae_of_compProd
    filter_upwards [h] with ω hω
    have hScaled : Integrable (fun t => K t ω)
        (canonicalPositiveKernel E ω) := by
      simpa [Function.uncurry, Prod.swap] using hω
    rw [canonicalPositiveKernel_apply] at hScaled
    exact (integrable_smul_measure
      (by exact_mod_cast (E.referenceDensity_pos ω).ne')
      (by simp)).mp hScaled
  have hKnPath : ∀ᵐ ω ∂μ, Integrable (fun t => K t ω)
      (FiniteVariationKernel.negativePathMeasure
        H.finiteVariationPart_isBoundedVariation ω) := by
    have h := hKnComp.ae_of_compProd
    filter_upwards [h] with ω hω
    have hScaled : Integrable (fun t => K t ω)
        (canonicalNegativeKernel E ω) := by
      simpa [Function.uncurry, Prod.swap] using hω
    rw [canonicalNegativeKernel_apply] at hScaled
    exact (integrable_smul_measure
      (by exact_mod_cast (E.referenceDensity_pos ω).ne')
      (by simp)).mp hScaled
  have hKernel := PredictableKernelMeasure.integral_signedMeasure_eq_integral_kernel
    (ℱ := ℱ) (μ := μ) (κp := canonicalPositiveKernel E)
    (κn := canonicalNegativeKernel E) hK hKp hKn
  change PredictableSignedMeasure.integral
      (PredictableKernelMeasure.signedMeasure ℱ μ
        (canonicalPositiveKernel E) (canonicalNegativeKernel E)) K = _
  calc
    PredictableSignedMeasure.integral
        (PredictableKernelMeasure.signedMeasure ℱ μ
          (canonicalPositiveKernel E) (canonicalNegativeKernel E)) K =
        ∫ ω, (∫ t, K t ω ∂canonicalPositiveKernel E ω) -
          (∫ t, K t ω ∂canonicalNegativeKernel E ω) ∂μ := hKernel
    _ = ∫ ω, E.referenceDensity ω • FiniteVariationPath.integral
        (H.finiteVariationPart_isBoundedVariation ω)
        (fun t => K t ω) ∂μ := by
      apply MeasureTheory.integral_congr_ae
      filter_upwards [hKpPath, hKnPath] with ω hωp hωn
      rw [canonicalPositiveKernel_apply, canonicalNegativeKernel_apply,
        integral_smul_nnreal_measure, integral_smul_nnreal_measure,
        FiniteVariationKernel.pathIntegral_eq_positive_sub_negative
          H.finiteVariationPart_isBoundedVariation ω (fun t => K t ω) hωp hωn]
      exact (smul_sub (E.referenceDensity ω)
        (∫ t, K t ω ∂FiniteVariationKernel.positivePathMeasure
          H.finiteVariationPart_isBoundedVariation ω)
        (∫ t, K t ω ∂FiniteVariationKernel.negativePathMeasure
          H.finiteVariationPart_isBoundedVariation ω)).symm
    _ = ∫ ω, FiniteVariationPath.integral
        (H.finiteVariationPart_isBoundedVariation ω)
        (fun t => K t ω) ∂E.referenceMeasure := by
      exact (integral_withDensity_eq_integral_smul
        E.referenceDensity_measurable _).symm

end SIntegrableFiniteVariationBridge

end FTAPTheorem42
