/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/
import FTAPTheorem42.Stochastic.Predictable.PredictableKernelMeasure
import FTAPTheorem42.Stochastic.Predictable.PredictableHahnVariationMass
import Mathlib.Probability.Kernel.Composition.IntegralCompProd

/-!
# Iterated integrals for predictable kernel measures

This file expands the signed measure on the predictable sigma algebra
generated by two finite kernels into the corresponding iterated kernel
integrals.  The hypotheses keep the representation bridge explicit: they
require strong predictability and integrability against both swapped kernel
measures.  No stochastic-integral closedness or pathwise realization is
asserted here.
-/

open Filter MeasureTheory ProbabilityTheory Set
open scoped ENNReal NNReal Topology ProbabilityTheory

namespace FTAPTheorem42

variable {Ω Time : Type*} [MeasurableSpace Ω]
  [MeasurableSpace Time] [LinearOrder Time] [OrderBot Time]
  [TopologicalSpace Time] [OpensMeasurableSpace Time]
  [OrderClosedTopology Time]

namespace PredictableKernelMeasure

/-- Integrating a predictable function against the measure generated by one
finite kernel is the corresponding iterated path integral. -/
theorem integral_predictableMeasure_eq_integral_kernel
    {ℱ : Filtration Time (inferInstance : MeasurableSpace Ω)}
    {μ : Measure Ω} {κ : Kernel Ω Time}
    [IsFiniteMeasure μ] [IsFiniteKernel κ]
    {K : Time → Ω → ℝ}
    (hK : StronglyMeasurable[ℱ.predictable] (Function.uncurry K))
    (hKκ : Integrable (Function.uncurry K) (swappedCompProd μ κ)) :
    (∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κ) =
      ∫ ω, ∫ t, K t ω ∂κ ω ∂μ := by
  have hKprod : StronglyMeasurable (Function.uncurry K) :=
    hK.mono (predictable_le_prod ℱ)
  have hKComp : Integrable
      (fun p : Ω × Time => Function.uncurry K (Prod.swap p))
      (μ ⊗ₘ κ) := by
    exact (integrable_map_measure hKprod.aestronglyMeasurable
      measurable_swap.aemeasurable).1 hKκ
  have hTrim :
      (∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κ) =
        ∫ p, Function.uncurry K p ∂swappedCompProd μ κ := by
    exact (MeasureTheory.integral_trim (predictable_le_prod ℱ) hK).symm
  have hMap :
      (∫ p, Function.uncurry K p ∂swappedCompProd μ κ) =
        ∫ p, Function.uncurry K (Prod.swap p) ∂(μ ⊗ₘ κ) := by
    change (∫ p, Function.uncurry K p ∂Measure.map Prod.swap (μ ⊗ₘ κ)) = _
    exact MeasureTheory.integral_map_of_stronglyMeasurable measurable_swap hKprod
  calc
    (∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κ) =
        ∫ p, Function.uncurry K p ∂swappedCompProd μ κ := hTrim
    _ = ∫ p, Function.uncurry K (Prod.swap p) ∂(μ ⊗ₘ κ) := hMap
    _ = ∫ ω, ∫ t, K t ω ∂κ ω ∂μ := by
      rw [MeasureTheory.Measure.integral_compProd hKComp]
      rfl

theorem integral_signedMeasure_eq_integral_kernel
    {ℱ : Filtration Time (inferInstance : MeasurableSpace Ω)}
    {μ : Measure Ω} {κp κn : Kernel Ω Time}
    [IsFiniteMeasure μ] [IsFiniteKernel κp] [IsFiniteKernel κn]
    {K : Time → Ω → ℝ}
    (hK : StronglyMeasurable[ℱ.predictable] (Function.uncurry K))
    (hKp : Integrable (Function.uncurry K) (swappedCompProd μ κp))
    (hKn : Integrable (Function.uncurry K) (swappedCompProd μ κn)) :
    PredictableSignedMeasure.integral (signedMeasure ℱ μ κp κn) K =
      ∫ ω, (∫ t, K t ω ∂κp ω) - (∫ t, K t ω ∂κn ω) ∂μ := by
  let hKprod : StronglyMeasurable (Function.uncurry K) :=
    hK.mono (predictable_le_prod ℱ)
  have hKpTrim : Integrable (Function.uncurry K)
      (predictableMeasure ℱ μ κp) := by
    change Integrable (Function.uncurry K)
      ((swappedCompProd μ κp).trim (predictable_le_prod ℱ))
    exact hKp.trim (predictable_le_prod ℱ) hK
  have hKnTrim : Integrable (Function.uncurry K)
      (predictableMeasure ℱ μ κn) := by
    change Integrable (Function.uncurry K)
      ((swappedCompProd μ κn).trim (predictable_le_prod ℱ))
    exact hKn.trim (predictable_le_prod ℱ) hK
  have hVp : VectorMeasure.Integrable
      ((predictableMeasure ℱ μ κp).toSignedMeasure :
        @VectorMeasure (Time × Ω) ℱ.predictable ℝ _ _)
      (Function.uncurry K) := by
    change Integrable (Function.uncurry K)
      (VectorMeasure.variation
        ((predictableMeasure ℱ μ κp).toSignedMeasure :
          @VectorMeasure (Time × Ω) ℱ.predictable ℝ _ _))
    rw [Measure.variation_toSignedMeasure]
    exact hKpTrim
  have hVn : VectorMeasure.Integrable
      ((predictableMeasure ℱ μ κn).toSignedMeasure :
        @VectorMeasure (Time × Ω) ℱ.predictable ℝ _ _)
      (Function.uncurry K) := by
    change Integrable (Function.uncurry K)
      (VectorMeasure.variation
        ((predictableMeasure ℱ μ κn).toSignedMeasure :
          @VectorMeasure (Time × Ω) ℱ.predictable ℝ _ _))
    rw [Measure.variation_toSignedMeasure]
    exact hKnTrim
  have htoP :
      (∫ᵛ p, Function.uncurry K p ∂•
          (predictableMeasure ℱ μ κp).toSignedMeasure) =
        ∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κp := by
    exact @FTAPTheorem42.PredictableSignedMeasure.vectorIntegral_toSignedMeasure
      (Time × Ω) ℱ.predictable (predictableMeasure ℱ μ κp) _ (Function.uncurry K)
  have htoN :
      (∫ᵛ p, Function.uncurry K p ∂•
          (predictableMeasure ℱ μ κn).toSignedMeasure) =
        ∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κn := by
    exact @FTAPTheorem42.PredictableSignedMeasure.vectorIntegral_toSignedMeasure
      (Time × Ω) ℱ.predictable (predictableMeasure ℱ μ κn) _ (Function.uncurry K)
  have hKpComp : Integrable
      (fun p : Ω × Time => Function.uncurry K (Prod.swap p))
      (μ ⊗ₘ κp) := by
    exact (integrable_map_measure hKprod.aestronglyMeasurable
      measurable_swap.aemeasurable).1 hKp
  have hKnComp : Integrable
      (fun p : Ω × Time => Function.uncurry K (Prod.swap p))
      (μ ⊗ₘ κn) := by
    exact (integrable_map_measure hKprod.aestronglyMeasurable
      measurable_swap.aemeasurable).1 hKn
  have hKpOuter : Integrable
      (fun ω => ∫ t, K t ω ∂κp ω) μ := by
    simpa [Function.uncurry, Prod.swap] using hKpComp.integral_compProd
  have hKnOuter : Integrable
      (fun ω => ∫ t, K t ω ∂κn ω) μ := by
    simpa [Function.uncurry, Prod.swap] using hKnComp.integral_compProd
  have hKpTrimIntegral :
      (∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κp) =
        ∫ p, Function.uncurry K p ∂swappedCompProd μ κp := by
    exact (MeasureTheory.integral_trim (predictable_le_prod ℱ) hK).symm
  have hKnTrimIntegral :
      (∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κn) =
        ∫ p, Function.uncurry K p ∂swappedCompProd μ κn := by
    exact (MeasureTheory.integral_trim (predictable_le_prod ℱ) hK).symm
  have hKpMapIntegral :
      (∫ p, Function.uncurry K p ∂swappedCompProd μ κp) =
        ∫ p, Function.uncurry K (Prod.swap p) ∂(μ ⊗ₘ κp) := by
    change (∫ p, Function.uncurry K p ∂Measure.map Prod.swap (μ ⊗ₘ κp)) = _
    exact MeasureTheory.integral_map_of_stronglyMeasurable measurable_swap hKprod
  have hKnMapIntegral :
      (∫ p, Function.uncurry K p ∂swappedCompProd μ κn) =
        ∫ p, Function.uncurry K (Prod.swap p) ∂(μ ⊗ₘ κn) := by
    change (∫ p, Function.uncurry K p ∂Measure.map Prod.swap (μ ⊗ₘ κn)) = _
    exact MeasureTheory.integral_map_of_stronglyMeasurable measurable_swap hKprod
  calc
    PredictableSignedMeasure.integral (signedMeasure ℱ μ κp κn) K =
        (∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κp) -
          ∫ p, Function.uncurry K p ∂predictableMeasure ℱ μ κn := by
      unfold PredictableSignedMeasure.integral signedMeasure
      rw [VectorMeasure.integral_sub_vectorMeasure hVp hVn, htoP, htoN]
    _ = (∫ p, Function.uncurry K p ∂swappedCompProd μ κp) -
          ∫ p, Function.uncurry K p ∂swappedCompProd μ κn := by
      rw [hKpTrimIntegral, hKnTrimIntegral]
    _ = (∫ p, Function.uncurry K (Prod.swap p) ∂(μ ⊗ₘ κp)) -
          ∫ p, Function.uncurry K (Prod.swap p) ∂(μ ⊗ₘ κn) := by
      rw [hKpMapIntegral, hKnMapIntegral]
    _ = (∫ ω, ∫ t, K t ω ∂κp ω ∂μ) -
          ∫ ω, ∫ t, K t ω ∂κn ω ∂μ := by
      rw [MeasureTheory.Measure.integral_compProd hKpComp,
        MeasureTheory.Measure.integral_compProd hKnComp]
      rfl
    _ = ∫ ω, (∫ t, K t ω ∂κp ω) - (∫ t, K t ω ∂κn ω) ∂μ := by
      rw [MeasureTheory.integral_sub hKpOuter hKnOuter]

end PredictableKernelMeasure

end FTAPTheorem42
