/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/
import FTAPTheorem42.Stochastic.DS.Lemma47.LocalizedHighMaximum

/-!
# Finite-variation increments forced by Lemma 4.7 excursions

The chronological clock is built from the first-localized martingale.  This
module samples the other canonical components at the same clock.  A negative
martingale excursion, outside the small `L²` gain-increment tail, forces a
positive finite-variation increment.  The final theorem starts from the
original high-martingale event, so neither the localized high event nor the
negative-excursion probability is left as an external input.
-/

open Filter MeasureTheory Set Topology
open scoped ENNReal MeasureTheory NNReal ProbabilityTheory

namespace FTAPTheorem42

variable {Ω : Type*} [MeasurableSpace Ω]

namespace Lemma47ExcursionStopping

/-- Sample `Y` at the chronological excursion clock generated by `X`. -/
noncomputable def sampleAlong
    (X Y : Process Ω) (T : ℝ≥0) (n : ℕ) : Ω → ℝ :=
  fun ω => Y (time X T n ω) ω

/-- Increment of `Y` along one excursion interval generated by `X`. -/
noncomputable def incrementAlong
    (X Y : Process Ω) (T : ℝ≥0) (n : ℕ) : Ω → ℝ :=
  fun ω => sampleAlong X Y T (n + 1) ω - sampleAlong X Y T n ω

/-- A right-continuous adapted process can be sampled measurably at an
excursion time generated by another right-continuous adapted process. -/
theorem stronglyMeasurable_sampleAlong
    {ℱ : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)}
    [ℱ.IsRightContinuous]
    {X Y : Process Ω} (hX : StronglyAdapted ℱ X)
    (hXRight : ∀ ω t,
      ContinuousWithinAt (X · ω) (Set.Ici t) t)
    (hY : StronglyAdapted ℱ Y)
    (hYRight : ∀ ω t,
      ContinuousWithinAt (Y · ω) (Set.Ici t) t)
    (T : ℝ≥0) (n : ℕ) :
    StronglyMeasurable (sampleAlong X Y T n) := by
  exact StoppingTimeRightApproximation.stronglyMeasurable_sample_of_boundedStoppingTime
    hY (time_isStoppingTime hX hXRight T n) (time_le X T n) hYRight

/-- Measurability of a component increment along an excursion interval. -/
theorem stronglyMeasurable_incrementAlong
    {ℱ : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)}
    [ℱ.IsRightContinuous]
    {X Y : Process Ω} (hX : StronglyAdapted ℱ X)
    (hXRight : ∀ ω t,
      ContinuousWithinAt (X · ω) (Set.Ici t) t)
    (hY : StronglyAdapted ℱ Y)
    (hYRight : ∀ ω t,
      ContinuousWithinAt (Y · ω) (Set.Ici t) t)
    (T : ℝ≥0) (n : ℕ) :
    StronglyMeasurable (incrementAlong X Y T n) :=
  (stronglyMeasurable_sampleAlong hX hXRight hY hYRight T (n + 1)).sub
    (stronglyMeasurable_sampleAlong hX hXRight hY hYRight T n)

/-- An indistinguishable component decomposition remains valid after
sampling both endpoints of an excursion interval. -/
theorem incrementAlong_eq_add_ae
    {μ : Measure Ω} {X Z A : Process Ω}
    (hDecomposition : ProcessIndistinguishable μ Z
      (fun t ω => X t ω + A t ω))
    (T : ℝ≥0) (n : ℕ) :
    incrementAlong X Z T n =ᵐ[μ]
      fun ω => increment X T n ω + incrementAlong X A T n ω := by
  filter_upwards [hDecomposition] with ω hω
  unfold incrementAlong sampleAlong increment sample
  rw [hω, hω]
  ring

/-- A negative martingale excursion forces a positive finite-variation
increment except on the event of a large whole-gain increment. -/
theorem probReal_finiteVariationIncrement_ge_half
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {X Z A : Process Ω}
    (hDecomposition : ProcessIndistinguishable μ Z
      (fun t ω => X t ω + A t ω))
    (T : ℝ≥0) (n : ℕ) {α error : ℝ}
    (hNegative : α ^ 2 < μ.real {ω | increment X T n ω ≤ -α})
    (hGainTail : μ.real {ω |
      α / 2 < |incrementAlong X Z T n ω|} ≤ error) :
    α ^ 2 - error < μ.real {ω |
      α / 2 ≤ incrementAlong X A T n ω} := by
  let E : Set Ω := {ω | increment X T n ω ≤ -α}
  let B : Set Ω := {ω | α / 2 < |incrementAlong X Z T n ω|}
  let P : Set Ω := {ω | α / 2 ≤ incrementAlong X A T n ω}
  have hsubset : E ≤ᵐ[μ] Set.union P B := by
    filter_upwards [incrementAlong_eq_add_ae hDecomposition T n] with ω hω
    intro hE
    by_cases hB : ω ∈ B
    · exact Set.mem_union_right P hB
    · apply Set.mem_union_left B
      change α / 2 ≤ incrementAlong X A T n ω
      change increment X T n ω ≤ -α at hE
      have hGainAbs : |incrementAlong X Z T n ω| ≤ α / 2 := by
        exact le_of_not_gt hB
      have hGainLower : -(α / 2) ≤ incrementAlong X Z T n ω :=
        (abs_le.mp hGainAbs).1
      rw [hω] at hGainLower
      linarith
  have hEUnion : μ.real E ≤ μ.real (P ∪ B) :=
    ENNReal.toReal_mono (by finiteness) (measure_mono_ae hsubset)
  have hUnion : μ.real E ≤ μ.real P + μ.real B :=
    hEUnion.trans (measureReal_union_le P B)
  change α ^ 2 < μ.real E at hNegative
  change μ.real B ≤ error at hGainTail
  change α ^ 2 - error < μ.real P
  linarith

end Lemma47ExcursionStopping

namespace SIntegrableProcessStoppingCalculus

variable {S : Process Ω}
  {ℱ : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)}
  [ℱ.IsRightContinuous]
  {μ : Measure Ω} [IsProbabilityMeasure μ] [SigmaFiniteFiltration μ ℱ]
  {D : SpecialSemimartingaleDecomposition S ℱ μ}

omit [SigmaFiniteFiltration μ ℱ] in
/-- A negative excursion of the explicit localized martingale forces a
positive increment of the actual localized strategy's finite-variation
component, with the precise gain-envelope Chebyshev error. -/
theorem lemma47Localized_finiteVariationIncrement_of_negativeExcursion
    (C : SIntegrableProcessStoppingCalculus D)
    (H : SIntegrableStrategy D)
    {scale : ℝ} (hScale : 0 < scale)
    (martingaleLevel gainLevel : ℝ)
    (gainEnvelope : Ω → ℝ)
    (hGainEnvelope : MemLp gainEnvelope (2 : ℝ≥0∞) μ)
    (hGainBound : ∀ᵐ ω ∂μ, ∀ t,
      |H.stochasticIntegral t ω| ≤ gainEnvelope ω)
    {normBound : ℝ} (hNormBound : 0 ≤ normBound)
    (hGainNorm : eLpNorm gainEnvelope (2 : ℝ≥0∞) μ ≤
      ENNReal.ofReal normBound)
    (T : ℝ≥0) {i : ℕ} {α : ℝ} (hα : 0 < α)
    (hNegative : α ^ 2 < μ.real {ω |
      Lemma47ExcursionStopping.increment
        (lemma47LocalizedMartingaleProcess H scale martingaleLevel
          gainLevel T) T i ω ≤ -α}) :
    α ^ 2 - (4 * scale * normBound / α) ^ 2 < μ.real {ω |
      α / 2 ≤ Lemma47ExcursionStopping.incrementAlong
        (lemma47LocalizedMartingaleProcess H scale martingaleLevel
          gainLevel T)
        (C.lemma47RescaleAndStopUpTo H scale martingaleLevel
          gainLevel T).finiteVariationPart T i ω} := by
  let X := lemma47LocalizedMartingaleProcess H scale martingaleLevel
    gainLevel T
  let L := C.lemma47RescaleAndStopUpTo H scale martingaleLevel gainLevel T
  let G := lemma47ScaledJumpEnvelope scale gainEnvelope
  have hGData := lemma47ScaledJumpEnvelope_memLp_and_norm
    (μ := μ) scale gainEnvelope hGainEnvelope
  have hGNorm : eLpNorm G (2 : ℝ≥0∞) μ ≤
      ENNReal.ofReal (scale * normBound) := by
    calc
      eLpNorm G (2 : ℝ≥0∞) μ =
          ENNReal.ofReal |scale| *
            eLpNorm gainEnvelope (2 : ℝ≥0∞) μ := hGData.2
      _ ≤ ENNReal.ofReal scale * ENNReal.ofReal normBound := by
        rw [abs_of_pos hScale]
        gcongr
      _ = ENNReal.ofReal (scale * normBound) := by
        rw [ENNReal.ofReal_mul hScale.le]
  have hLBound : ∀ᵐ ω ∂μ, ∀ t, t ≤ T →
      |L.stochasticIntegral t ω| ≤ G ω := by
    filter_upwards [C.lemma47RescaleAndStopUpTo_stochasticIntegral H scale
      martingaleLevel gainLevel T, hGainBound] with ω hComponent hBound
    intro t _
    change |stochasticIntegral
      (C.lemma47RescaleAndStopUpTo H scale martingaleLevel
        gainLevel T) t ω| ≤
        lemma47ScaledJumpEnvelope scale gainEnvelope ω
    rw [hComponent t, abs_mul]
    change |scale| * |MeasureTheory.stoppedProcess H.stochasticIntegral
        (lemma47FirstPassageUpTo H martingaleLevel gainLevel T) t ω| ≤
      |scale| * |gainEnvelope ω|
    apply mul_le_mul_of_nonneg_left _ (abs_nonneg scale)
    rw [← RightContinuousStoppedMartingale.sample_boundedTime_eq_stoppedProcess]
    exact (hBound _).trans (le_abs_self (gainEnvelope ω))
  have hGainTail : μ.real {ω |
      α / 2 < |Lemma47ExcursionStopping.incrementAlong
        X L.stochasticIntegral T i ω|} ≤
      (4 * scale * normBound / α) ^ 2 := by
    have hTail :=
      FactorialChronologicalGrid.probReal_sampledDifference_gt_le
        L.stochasticIntegral_isStronglyAdapted
        L.stochasticIntegral_isRightContinuous T
        (Lemma47ExcursionStopping.time X T (i + 1))
        (Lemma47ExcursionStopping.time X T i)
        (Lemma47ExcursionStopping.time_le X T (i + 1))
        (Lemma47ExcursionStopping.time_le X T i)
        hGData.1 hLBound (mul_nonneg hScale.le hNormBound)
        (by positivity : 0 < α / 2) hGNorm
    change μ.real {ω | α / 2 <
        |L.stochasticIntegral
            (Lemma47ExcursionStopping.time X T (i + 1) ω) ω -
          L.stochasticIntegral
            (Lemma47ExcursionStopping.time X T i ω) ω|} ≤ _
    apply hTail.trans_eq
    field_simp
    ring
  have hMartingale : ProcessIndistinguishable μ L.martingalePart X := by
    exact C.lemma47RescaleAndStopUpTo_martingalePart H scale
      martingaleLevel gainLevel T
  have hDecomposition : ProcessIndistinguishable μ L.stochasticIntegral
      (fun t ω => X t ω + L.finiteVariationPart t ω) :=
    L.integral_decomposition.trans
      (hMartingale.add (ProcessIndistinguishable.refl μ L.finiteVariationPart))
  exact Lemma47ExcursionStopping.probReal_finiteVariationIncrement_ge_half
    hDecomposition T i hNegative hGainTail

/-- Starting from the original high-martingale witness, the actual first
localization has positive finite-variation increments on every retained
excursion interval, up to the explicit vanishing gain error. -/
theorem lemma47FirstLocalized_finiteVariationExcursion_of_originalHigh
    (C : SIntegrableProcessStoppingCalculus D)
    (hUsual : Filtration.UsualConditions μ ℱ)
    (H : SIntegrableStrategy D)
    (hMartingaleLeft : ProcessHasLeftLimits H.martingalePart)
    (hMartingaleZero : H.martingalePart 0 =ᵐ[μ] 0)
    {n : ℕ} (hn : 0 < n)
    {martingaleLevel : ℝ} (hMartingaleLevel : 0 ≤ martingaleLevel)
    {gainLevel : ℝ} (hGainLevel : 0 < gainLevel)
    (gainEnvelope : Ω → ℝ)
    (hGainEnvelope : MemLp gainEnvelope (2 : ℝ≥0∞) μ)
    (hGainBound : ∀ᵐ ω ∂μ, ∀ t,
      |H.stochasticIntegral t ω| ≤ gainEnvelope ω)
    {normBound : ℝ} (hNormBound : 0 ≤ normBound)
    (hGainNorm : eLpNorm gainEnvelope (2 : ℝ≥0∞) μ ≤
      ENNReal.ofReal normBound)
    (hJumpNumeric : 6 * normBound ≤ (n : ℝ) ^ 2)
    {T : ℝ≥0} (hT : 0 < T)
    {k : ℕ} (hk : 0 < k) {R α : ℝ}
    (hR : 0 < R) (hRScale : R < lemma47FirstScale n * martingaleLevel)
    (hα : 0 < α) (hαOne : α ≤ 1)
    (hOriginalHigh : 8 * α < μ.real {ω |
      martingaleLevel <
        FactorialChronologicalGrid.finiteHorizonAbsoluteEnvelope
          H.martingalePart T ω})
    (hGainError : (normBound / gainLevel) ^ 2 ≤ α)
    (hExcursionError : (4 * (k : ℝ) / R) ^ 2 ≤ α)
    {i : ℕ} (hi : i < k) :
    α ^ 2 -
        (4 * lemma47FirstScale n * normBound / α) ^ 2 <
      μ.real {ω | α / 2 ≤
        Lemma47ExcursionStopping.incrementAlong
          (lemma47LocalizedMartingaleProcess H (lemma47FirstScale n)
            martingaleLevel gainLevel T)
          (C.lemma47RescaleAndStopUpTo H (lemma47FirstScale n)
            martingaleLevel gainLevel T).finiteVariationPart T i ω} := by
  have hNegative := C.lemma47FirstLocalized_negativeExcursion_of_originalHigh
    hUsual H hMartingaleLeft hMartingaleZero hn hMartingaleLevel
    hGainLevel gainEnvelope hGainEnvelope hGainBound hNormBound hGainNorm
    hJumpNumeric hT hk hR hRScale hα hαOne hOriginalHigh hGainError
    hExcursionError hi
  have hScale : 0 < lemma47FirstScale n := by
    unfold lemma47FirstScale
    positivity
  exact C.lemma47Localized_finiteVariationIncrement_of_negativeExcursion
    H hScale martingaleLevel gainLevel gainEnvelope hGainEnvelope hGainBound
    hNormBound hGainNorm T hα hNegative

end SIntegrableProcessStoppingCalculus

end FTAPTheorem42
